### ISSUE TITLE
Samplesheets: Add diff comparison for sheet versions

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1007]
Suggested by @holtgrewe. Ideally, should be done together with #754, #773 and any other planned versioning UI improvements.

## Spec

- Choose versions to compare in UI
    * Add simple form controls to the top of the sheet version list
    * 2 dropdowns to choose from, similar to comparison UI in GitLab
    * Allowed to anyone who can access the version list (that is, use the same permission)
- Add separate Django view for displaying compare results
    * Pull original ISAtabs from db
    * Use `difflib.HtmlDiff`

## Tasks

- [x] Add version selection UI in version list
- [x] Add comparison result view
- [ ] Implement comparison logic
- [x] Add permission and view tests

**Comment by mikkonie** [comment]
unassigned @stolpeo
