### ISSUE TITLE
Upgrade to Bootstrap 4.5.x

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1011]
The samplesheets vue app is already using this version thanks to `bootstrap-vue` being upgraded. Not very logical to assume different version for Django stuff.

Will test this first in SODAR Core to make sure there are no major complications, see undefined##undefined.

## Tasks

- [x] Upgrade and test for SODAR Core
- [x] Upgrade and test for SODAR
- [x] Update [ansible-role-sodar-server](https://github.com/bihealth/ansible-role-sodar-server/)
