### ISSUE TITLE
Update docs and tests for our current iRODS setup

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1028]
The CUBI iRODS setup has recently changed so that a PEP rule automatically generating MD5 checksums for each upload is no longer used on the server. Hence, iRODS put/sync commands should be used with the `-k` flag.

Alas, our dev docs and dev environment still assume we use a specific rule file `omics.re` on the iRODS server and the `-k` flag isn't needed. This needs to be fixed.

**Q:** Does the irodsbackend `put()` method actually support this flag? Need to check..

## Tasks

- [ ] Update tests to correctly use `put()`
- [ ] Remove the `omics.re` requirement from docs
- [x] Update docs to suggest using `-k`
- [ ] Update `sodar_docker_env` accordingly (see sodar_docker_env#12)

**Comment by mikkonie** [comment]
No longer relevant due to sodar-docker-compose, closing.
