### ISSUE TITLE
Samplesheets Vue app unit test improvements

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1037]
Stuff left over from #750, because I wanted to wrap up that mega issue and continue with more pressing stuff to finalize the v0.9 milestone.

## Tasks

- [ ] Set up global warning suppression
- [ ] Add extra editing tests after implementing #1036
- [ ] Test `AgGridDragSelect`?
- [ ] Solutions for `bootstrap-vue` testing issues? (see #1030 and #1034)
- [ ] Set up coverage checking for both Python & Vue.js?
