### ISSUE TITLE
Add landing zone collection enforcement

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1050]
(Note: Edited from original issue)

We need to have the ability to enforce writing access to specific collections under a landing zone. This gets rid of the often-repeating problem of people uploading data into wrongly named collections due to e.g. typos, which are not properly linked in the SODAR UI.

This needs to be coupled with the collection creation feature, so no extra checks are required beyond allowing user access only to subcollections instead of the landing zone root.

## Spec

- Add form field for enforcing collections into `LandingZone`
    * True by default, allows opt-out
- Add the field into REST API as well
- IF set True and collections are created, set user read/write access only to created collections
    * ELSE set up landing zone as is done currently

## Tasks

- [x] Add field in forms
- [x] Add behaviour into taskflow
- [x] Add field read/write in REST API
- [x] Update tests
- [x] Update docs

**Comment by eudesbarbosa** [comment]
**Priority**: Not crucial, but very nice to have.

**Justification**: Manual transfer of data to SODAR is error prone, so any additional validation would help. Concrete example: large batches coming from external sequencing facilities like the one in Cologne.
Regarding `irodsorphans`, it is not available for users so it is not possible to see the collection in SODAR and request the deletion. I also don't know how often there orphan clean up is performed - once every six months?

**Comment by mikkonie** [comment]
The one issue I see is that this will create a lot of new tasks for the taskflow, potentially making zone creation slightly slower than before for huge studies. The difference shouldn't be critical though. This can't really be helped until we implement #1510.

**Comment by mikkonie** [comment]
Done.
