### ISSUE TITLE
Samplesheets: Update search to current SODAR Core implementation

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1065]
What it says on the tin.

## Tasks

- [x] Update `search()` and `find()` implementations
- [x] Update `irodsbackend` search to accept multiple terms
- [x] Add tests for `find()`
- [x] Add tests for search view with samplesheets input
