### ISSUE TITLE
Samplesheets: Add sheet creation from templates

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1068]
We previously discussed some temporary way of implementing template-based creation of sample sheets. However, after looking at cubi-tk I thought the cookiecutter-based generation of sheets from templates could be easily wrapped into a Django form. After a couple of hours of experimentation it's already mostly working, so I'd say this is the way to go!

## Tasks

- [x] Add forms for template selection and filling
- [x] "Import" sheets internally from the generated ISAtab files
- [x] Limit template selection to ones working in cubi-tk
- [x] Add permission and view tests (of course)
- [x] Update docs (do we actually have docs)

## Temp Tasks

- [x] Fix forcing value for selections containing empty option
- [x] Fix `assay_technology_types` errors
- [ ] Fix single cell template crash (see pull request in cubi-tk)
- [ ] Fix "Missing protocol reference" error in microarray/tumor creation with default values (problem in cubi-tk)
