### ISSUE TITLE
Cleanup for v0.10.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1077]
Tiny tasks here as usual.

## Tasks

- [x] Shorten command test function names
- [x] Suppress `console.log()` in `ColumnConfigModal.spec.js`
- [x] Long lines in `samplesheets.tests.test_views_taskflow`
- [x] Add newline to `.gitignore`
- [x] Cleanup `production.py`
- [x] Mention additonal apps in `README`
- [x] Add missing #1112 reference in changelog
- [x] Cleanup code
