### ISSUE TITLE
Samplesheets: Enable public iRODS access for public projects

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1100]
Once undefined##undefined is implemented, we also need to have functionality to enable/disable public iRODS access to sample data repositories in specific projects.

**NOTE:** Most of the work actually happens in SODAR Taskflow, but I'm drafting this issue here for clarity's sake.

## How Sample Data Access Currently Works

- User group gets created for each project
- User group gets read access to sample data collection and below
- User is added/removed from project group when roles are given/removed

## Requirements

- IF `handle_project_update()` in the samplesheets project app plugin is called
- AND `public_guest_access` value is changed or project is freshly created
- THEN grant/revoke read access for sample collection for all logged-in users
    * IF anonymous access is allowed on the site with `PROJECTROLES_ALLOW_ANOMYMOUS=True`
    * THEN also grant/revoke anonymous read access to the project

## Spec

- Grant/revoke project read-only access to the `public` user group for logged in users
- If anonymous users are allowed, create iRODS ticket for anonymous read access
    * Save ticket to project setting (non-modifiable in form)
    * Modify UI to provide ticket URL instead of standard DavRods URL if user viewing the project is anonymous

## Tasks

- [x] Add public user group updating in SODAR and Taskflow
- [x] Add updating logic to iRODS collection generation
- [x] Add public user group update tests
- [x] Add anonymous ticket creation/revoking
- [x] Add ticket URL rendering
- [x] Disable export button for anonymous user (for now)
- [x] Add ticket tests
