### ISSUE TITLE
Upgrade to SODAR Core v0.10.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1113]
What it says on the tin. This also requires the following:

## Tasks

- [x] Upgrade all dependencies (Django 3.2 etc)
- [x] Update project for Django 3.2
- [x] Update Python to v3.7+
- [x] Update all icons
- [x] Update icons in vue app and ensure it works
- [x] Update documentation
- [ ] Update Ansible playbooks

## Temp TODO

- [x] Fix too much left padding for icons in list buttons
- [x] Ensure spinners work everywhere
- [x] Spinner not hidden from iRODS status badge once queried
- [x] Fix edit info button vertical alignment vs. info badges
