### ISSUE TITLE
Cleanup for GitHub release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1119]
Already pushed this to GitHub, but need to clean it up a bit to be respectable.

## Tasks

- [x] Add note to readme about being under development and poorly documented
- [x] Update CUBI gitlab links to github where applicable
- [x] Set up CI (#1033)
- [ ] Cleanup code
