### ISSUE TITLE
Set up CI with iRODS and Taskflow

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1168]
We should try to set up CI so that we can run all tests, even those requiring iRODS.

In GitLab this wasn't possible (at least recently), since it doesn't support a Docker network required for SODAR Taskflow callbacks. The new implementation in #691 no longer requires such callbacks since we don't have a separate microservice.

We can use our own Docker image and technically, there should be few issues.

Once this is done, it's possible to remove all skips for iRODS. At that point we can also look into #1395. 

## Tasks

- [x] Set up CI in Github Actions
- [x] ~~Set up CI in Gitlab~~ Nope, see comments
- [x] Remove test skips once working
- [x] Simplify postgres setup with a single server

**Comment by mikkonie** [comment]
Once this has been set up, should also remove `TASKFLOW_ENABLED`, `TASKFLOW_SKIP_MSG` and related variables & skips from unit tests, as they will no longer be necessary.

**Comment by mikkonie** [comment]
The setup now works 100% in Github Actions, but it seems the same is hard to achieve in Gitlab CI. For example, we can't have two database servers with identical settings, requiring manual database setup or a modified iRODS image.

Gitlab is secondary for us anyway since this project is primarily maintained on Github. Hence, I decided to drop support for CI in the former.

**Comment by mikkonie** [comment]
Done.
