### ISSUE TITLE
Samplesheets: Add app to manual

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1180]
Not sure why not there already.

## Spec

- Overview
- Browsing
    * Display and explain contents of view and usage when browsing sheets
    * Describe iRODS shortcuts and linking briefly, link to detailed section
    * Mention that uploading data is done via Landingzones app
- Importing and Creating Sheets
    * Detail import and creation from templates
    * Include iRODS collection creation etc.
    * Mention parser warnings here!
- Exporting Sheets
    * Discuss exporting sample sheets
- Editing Sheets
    * Document the entire editor
    * Include also column configuration
    * Include sheet replacing
    * Explicitly mention features **not** yet implemented
- Version Management
    * Managing saved versions
    * Diff comparison
- iRODS Access Tickets
- iRODS Delete Requests
- iRODS Data Linking
    * Describe linking of data for studies and assays
    * Link to or integrate with "Advanced Metadata Topics" where appropriate
- App settings
    * **TBD:** Probably better to integrate all SODAR apps into the project create/upate doc in the UI section?

## Tasks

- [x] Add Overview
- [x] Add Browsing
- [x] Update IGV section to remove repetition and improve screenshots
- [x] Add Sheet Import/Creation
- [x] Add Sheet Export
- [x] Add Sheet Editing
- [x] Add Version Management
- [x] Add iRODS Access Tickets
- [x] Add iRODS Delete Requests
- [x] Add iRODS Data Linking
- [x] Mention cache updating
- [x] ~~Add App Settings~~ Will do in another task

**Comment by mikkonie** [comment]
marked the task **Add Overview** as completed

**Comment by mikkonie** [comment]
mentioned in commit 70fc1a191dc68ea942649ae0cda163828d124739

**Comment by mikkonie** [comment]
mentioned in commit 2a19822498a1fbf76f2ea95d8113de26ec750069

**Comment by mikkonie** [comment]
marked the task **Add Browsing** as completed

**Comment by mikkonie** [comment]
mentioned in commit 2cd2027d85049d5c22d30086fdaac5ea6738f060

**Comment by mikkonie** [comment]
mentioned in commit c705cbf5951fcf82ea13bfc10ee444e6c5461cef

**Comment by mikkonie** [comment]
mentioned in commit c4b4e785a28f749beae838b16023b653a71f694d

**Comment by mikkonie** [comment]
mentioned in commit 016835b3d2b76bfc68ea75f545414e44b931b435

**Comment by mikkonie** [comment]
mentioned in commit 518d217d13f94da0b8bd133abacaa0874401e084

**Comment by mikkonie** [comment]
marked the task **Add Sheet Import/Creation** as completed

**Comment by mikkonie** [comment]
mentioned in commit b75fb562f78ed0974d3ad89f12613a9784b1c982

**Comment by mikkonie** [comment]
marked the task **Add Sheet Export** as completed

**Comment by mikkonie** [comment]
marked the task **Add iRODS Data Linking** as completed

**Comment by mikkonie** [comment]
mentioned in commit f8450191eed1081d55c49fd9ad320b2115b52ce1

**Comment by mikkonie** [comment]
mentioned in commit f7d61bff7c03716fd6b5f4b015ef1aa1229f34e7

**Comment by mikkonie** [comment]
mentioned in commit 42cd9a33f87a1a0d7063692759bf9a52d5a3b2e8

**Comment by mikkonie** [comment]
mentioned in commit f023280738db4ca91e468dd2ac671f97f293ad1e

**Comment by mikkonie** [comment]
mentioned in commit fddf2c955b182ac1377cd5e26880fe3696492569

**Comment by mikkonie** [comment]
mentioned in commit 76ba7d7376beeeecde24ba829b7763a4ccd93fb0

**Comment by mikkonie** [comment]
mentioned in commit e31c3d47b8ccb94440a58195b3b22215441cccf3

**Comment by mikkonie** [comment]
mentioned in commit a809332f9363cd92ebb200f339e2a8cf7d399145

**Comment by mikkonie** [comment]
mentioned in commit 5a6c02eab9644af0277206332289f7ed122afc1c

**Comment by mikkonie** [comment]
mentioned in commit 2bac7bf786aae9d8f2cfea7d4869aa29a4844f78

**Comment by mikkonie** [comment]
marked the task **Add Sheet Editing** as completed

**Comment by mikkonie** [comment]
mentioned in commit 5505fc6acd89c22b3472610c9420ddad89cbbe6e

**Comment by mikkonie** [comment]
mentioned in commit ff0b01943690409eb4397fa2168f0a56fc533f5b

**Comment by mikkonie** [comment]
mentioned in commit 044fbd6dd68d14a3576dab35afe3402f34a5670f

**Comment by mikkonie** [comment]
mentioned in commit c357063c32a251af5f84b705a3435e137107b55c

**Comment by mikkonie** [comment]
mentioned in commit 496ac278b3fe23d8d23c1771bb22647d83dbbd9f

**Comment by mikkonie** [comment]
mentioned in commit cea53d727432dfff4424f44e8c05a763665f7080

**Comment by mikkonie** [comment]
mentioned in commit 57a4a188fb6c633d12d9069a7536593b0d2a2804

**Comment by mikkonie** [comment]
mentioned in commit 01384d35effba03f7e5a49e1cb9d425a4c5cb516

**Comment by mikkonie** [comment]
mentioned in commit c1ebea70af87d23ae6802578244323829c2314ff

**Comment by mikkonie** [comment]
mentioned in commit f3fea631f2f5bc815a5a56ab10561f3ce1aa02af

**Comment by mikkonie** [comment]
mentioned in commit 6378c082a13c5b74032a4842ae117a3d36a860ad

**Comment by mikkonie** [comment]
marked the task **Add Version Management** as completed

**Comment by mikkonie** [comment]
mentioned in commit f5e78d6fdbe833029b3ca38225bd55eabfa7ebc7

**Comment by mikkonie** [comment]
marked the task **Add iRODS Delete Requests** as completed

**Comment by mikkonie** [comment]
mentioned in commit 39bd02ff6c6d468780bf3e7e26b27a17f9db0245

**Comment by mikkonie** [comment]
mentioned in commit 7e76d12da679453394c0fa0ccfeb793c7d50a85e

**Comment by mikkonie** [comment]
mentioned in commit eeca926e8f4b1251d5c94d83686fc1b71c8c2b3f

**Comment by mikkonie** [comment]
mentioned in commit 7e3ba59c448fede81302fbecc043c574d0b30e38

**Comment by mikkonie** [comment]
mentioned in commit 22bce9b972b1235a8f9eab0a63d492f590cbdbd8

**Comment by mikkonie** [comment]
mentioned in commit ba4115c190bc8d32468337d988d00f356a47e20c

**Comment by mikkonie** [comment]
mentioned in commit c58c65529f16ddcba4936b6913e427141e2fbb65

**Comment by mikkonie** [comment]
mentioned in commit 653fb5c4e760e2f854ce5a5e86c01c12d8710ccb

**Comment by mikkonie** [comment]
mentioned in commit 4ea9ce1e37ff1a9e614bb2da295a483adc4623fe

**Comment by mikkonie** [comment]
mentioned in commit 75b3cc303ea5959fc29b522441e11776a46ea5c8

**Comment by mikkonie** [comment]
mentioned in commit 3f873877c2c69c05238894a37d3e871bb8218c01

**Comment by mikkonie** [comment]
mentioned in commit aa56f4ebb67b2f186ba4f83cfaee9a61bfdbb84a

**Comment by mikkonie** [comment]
mentioned in commit 31e6b4ac45a589c2a717f47209dcfb1517542a89

**Comment by mikkonie** [comment]
mentioned in commit 3707ce561c6f29a378743cd5f2489db4ba93a38b

**Comment by mikkonie** [comment]
mentioned in commit 106109a0d7eeeb9cd2fc3bd3c02d04b370ee51a0

**Comment by mikkonie** [comment]
mentioned in commit 8fa38023974cbbad2a785ca9351ede54201cb12c

**Comment by mikkonie** [comment]
mentioned in commit 33ec858fa7f81828c0f80a36e1941f1e2ee46d80

**Comment by mikkonie** [comment]
mentioned in commit 71e0e91d408ac6b0319222489a51f793041081e5

**Comment by mikkonie** [comment]
mentioned in commit b28f9a12b37f4c1f568781556cb31299a1107866

**Comment by mikkonie** [comment]
mentioned in commit 3e4b10d662678651bedbe77fd111917714308b4b

**Comment by mikkonie** [comment]
mentioned in commit f8a64f7b519e40ff4b94dccaa27ec9a6c20d28e2

**Comment by mikkonie** [comment]
mentioned in commit b7258ca97826e1fc00af9dde92b01ad85f2932ce

**Comment by mikkonie** [comment]
mentioned in commit e726607e9fd9fde122cd8c0519ea6b6cd0bb084e

**Comment by mikkonie** [comment]
mentioned in commit 2a506351aa67cb30493cf57355e6e3ca5d3396dd

**Comment by mikkonie** [comment]
mentioned in commit 970090e1c4400b6ecb6de04ce5f3cc8ae74b8618

**Comment by mikkonie** [comment]
mentioned in commit b8c73495fbc7cc3995eafa2c1380f49b3766fd62

**Comment by mikkonie** [comment]
mentioned in commit d271c6973dc82e1d691d64fe93be8942b5da4072

**Comment by mikkonie** [comment]
mentioned in commit 8c924e5c6033ad5adf616901afdc3e24ab06617e

**Comment by mikkonie** [comment]
mentioned in commit 0d67910b50f5c28ee5de4f333def07d27502730f

**Comment by mikkonie** [comment]
marked the task **Add iRODS Access Tickets** as completed

**Comment by mikkonie** [comment]
marked the task **Mention cache updating** as completed

**Comment by mikkonie** [comment]
marked the task **Update IGV section to remove repetition and improve screenshots** as completed

**Comment by mikkonie** [comment]
mentioned in commit 974b2cf1f080ec35413ea559e4b235499a014890

**Comment by mikkonie** [comment]
mentioned in commit e03a5a2c8d904ac722ca43f9b1c38b08cff9e084

**Comment by mikkonie** [comment]
marked the task **~~Add App Settings~~ Will do in another task** as completed

**Comment by mikkonie** [comment]
Done. Phew!
