### ISSUE TITLE
Landingzones: Add app to manual

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1181]
See also #1180.

## Tasks

- [x] Add overview
- [x] Add creation doc
- [x] Add management doc
- [x] Link to sample sheets doc where applicable
- [ ] Refactor proteomics doc for duplicate info

**Comment by mikkonie** [comment]
mentioned in commit b482b0eadd5173d9e8c27e5fe873f95f6137e159

**Comment by mikkonie** [comment]
mentioned in commit 22edd2034f5d9f92ff66cb64a5e3ed038a0c6d20

**Comment by mikkonie** [comment]
mentioned in commit 36f57d5f5a2119ef1c261ee183cc85536ca00723

**Comment by mikkonie** [comment]
marked the task **Add overview** as completed

**Comment by mikkonie** [comment]
marked the task **Add creation doc** as completed

**Comment by mikkonie** [comment]
marked the task **Add management doc** as completed

**Comment by mikkonie** [comment]
mentioned in commit 07be3c42a5289f0ca72db27bd5e0c941b624140c

**Comment by mikkonie** [comment]
marked the task **Link to sample sheets doc where applicable** as completed

**Comment by mikkonie** [comment]
Done. Didn't touch the proteomics doc for now.
