### ISSUE TITLE
Cleanup for v0.10.1 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1190]
Minor tasks here.

## Tasks

- [x] Remove commented `chunk-vendors` include from samplesheets template
- [x] Fix SODAR Core version number ref in changelog
- [x] Clean CUBI references in default django settings
- [x] Update deployment section in dev docs to recommend Docker
