### ISSUE TITLE
Docker build and entrypoint issues

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1194]
Working on fixing a bunch of Docker build and entrypoint issues.

## Tasks

- [x] Static files not found (1)
- [x] Collectstatic fails to locate `local-static` (2)
- [x] ~~Complaints about missing migrations for already migrated apps~~ (3)
- [ ] Vue app crash (see #1198)

1. Fixed
2. Fixed
3. See #1196
