### ISSUE TITLE
Landingzones: Send app alerts to zone owner for actions

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1204]
Together with #1203, we should also send app alerts to zone owner for results of all zone actions. That way they wouldn't necessarily have to be looking at the zone list view to verify the status.

## Tasks

- [x] Add alert for moved zone
- [x] Add alert for failed attempt at moving
- [x] Add/update tests

**Comment by mikkonie** [comment]
marked the task **Add alert for moved zone** as completed

**Comment by mikkonie** [comment]
marked the task **Add alert for failed attempt at moving** as completed

**Comment by mikkonie** [comment]
mentioned in commit a5c27ba06ae7fcc8b067af3b0c6cc4ccf290a2b8

**Comment by mikkonie** [comment]
mentioned in commit 63863a504d3a9158f42710228137dd9b5bb91441

**Comment by mikkonie** [comment]
mentioned in commit 130d6be2876a2bb3f2ff3bd76fc0f736a17276a8

**Comment by mikkonie** [comment]
marked the task **Add/update tests** as completed

**Comment by mikkonie** [comment]
Done.

**Comment by mikkonie** [comment]
mentioned in commit 89fd9ea643af63dbbb057e82a9d32db12115c4f5
