### ISSUE TITLE
Cleanup for v0.11.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1228]
As usual, collecting tiny cleanup tasks here.

## Tasks

- [x] Fix "UI" mentions in changelog entries for issue #1000
- [x] Fix broken travis.yml notation in changelog
- [x] Update all `*@bihealth.de` emails
- [x] Add landingzones irods dir feature to major changes in docs
- [x] Cleanup `get_taskflow_sync_data()` line length
- [x] Remove `setDefault` debug print from `ColumnToggleModal`
- [x] Make landingzones app alert messages consistent with projectroles (`.`)
- [x] Remove redundant `studyUuid` attribute from study div in `App.vue`
- [x] Fix samplesheets nav section hiding (see edit mode!)
- [x] Fix ticket access issue ref in changelog (should be #1302)
- [x] Remove redundant `ADMIN_URL` redefinition from `production.py`
- [x] Fix comment for `SHEETS_SYNC_INTERVAL` in `base.py`
- [x] Fix mentions of issue #1301 in `CHANGELOG`
- [x] Fix "Proxy Configuration" formatting in IGV setup doc
- [x] Add note about browser support to docs (both general section and IGV instructions)
- [x] Rename `*_value()` to `*_val()` in `samplesheets.io` (#627)
- [x] Do #734
- [x] Do #810
- [x] Add `IRODS_SODAR_AUTH` to `IRODS_INFO_SETTINGS` in irodsbackend
- [x] Clarify "hybridization assay name" in advanced metadata doc
- [x] Fix formatting error in `app_samplesheets_version` doc
- [x] Add missing #1318 reference to CHANGELOG

**Comment by mikkonie** [comment]
marked the task **Fix "UI" mentions in changelog entries for issue #1000** as completed

**Comment by mikkonie** [comment]
mentioned in commit 6028ce07f73e548cd73992d9e780a95ec746fe93

**Comment by mikkonie** [comment]
marked the task **Update all `*@bihealth.de` emails** as completed

**Comment by mikkonie** [comment]
marked the task **Remove `setDefault` debug print from `ColumnToggleModal`** as completed

**Comment by mikkonie** [comment]
mentioned in commit 86cb57e4fd25578dae61728bf71234b80926a0ff

**Comment by mikkonie** [comment]
marked the task **Remove redundant `ADMIN_URL` redefinition from `production.py`** as completed

**Comment by mikkonie** [comment]
marked the task **Fix formatting error in `app_samplesheets_version` doc** as completed

**Comment by mikkonie** [comment]
marked the task **Add missing #1318 reference to CHANGELOG** as completed

**Comment by mikkonie** [comment]
marked the task **Fix broken travis.yml notation in changelog** as completed

**Comment by mikkonie** [comment]
marked the task **Fix mentions of issue #1301 in `CHANGELOG`** as completed

**Comment by mikkonie** [comment]
marked the task **Do #734** as completed

**Comment by mikkonie** [comment]
marked the task **Do #810** as completed

**Comment by mikkonie** [comment]
marked the task **Fix ticket access issue ref in changelog (should be #1302)** as completed

**Comment by mikkonie** [comment]
mentioned in commit 37438555bef35fa2f5e288a6106a9c4a3ced7a1b

**Comment by mikkonie** [comment]
marked the task **Add landingzones irods dir feature to major changes in docs** as completed

**Comment by mikkonie** [comment]
marked the task **Cleanup `get_taskflow_sync_data()` line length** as completed

**Comment by mikkonie** [comment]
marked the task **Rename `*_value()` to `*_val()` in `samplesheets.io` (#627)** as completed

**Comment by mikkonie** [comment]
marked the task **Make landingzones app alert messages consistent with projectroles (`.`)** as completed

**Comment by mikkonie** [comment]
marked the task **Add `IRODS_SODAR_AUTH` to `IRODS_INFO_SETTINGS` in irodsbackend** as completed

**Comment by mikkonie** [comment]
mentioned in commit e2d07e1be42c44442db7b4022f793e45add6cc37

**Comment by mikkonie** [comment]
marked the task **Remove redundant `studyUuid` attribute from study div in `App.vue`** as completed

**Comment by mikkonie** [comment]
marked the task **Fix samplesheets nav section hiding (see edit mode!)** as completed

**Comment by mikkonie** [comment]
marked the task **Fix comment for `SHEETS_SYNC_INTERVAL` in `base.py`** as completed

**Comment by mikkonie** [comment]
marked the task **Add note about browser support to docs (both general section and IGV instructions)** as completed

**Comment by mikkonie** [comment]
marked the task **Fix "Proxy Configuration" formatting in IGV setup doc** as completed

**Comment by mikkonie** [comment]
marked the task **Clarify "hybridization assay name" in advanced metadata doc** as completed

**Comment by mikkonie** [comment]
mentioned in commit 8473c4ea3ea64edb54375508bbe41b4ec430e452

**Comment by mikkonie** [comment]
mentioned in commit eeffdd956868a21ebebdc73a03e3f9d1db147573

**Comment by mikkonie** [comment]
Done.
