### ISSUE TITLE
Landingzones: Minor UI improvements

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1235]
Since I'm already working on a lot of landingzones stuff, might take 15 minutes to improve a few things that irk me:

- Display empty "Your Zones" card if zones do not exist
    * This would be more consistent with the rest of the site, see also #1097 
- Improve table columns if possible
    * Status info column is too narrow
    * Assay column takes up too much space
- Force wrapping of long words in status info message
    * These can explode the entire table layout

## Tasks

- [x] Display empty Your Zones card
- [x] Improve table column layout
- [x] Force status info wrapping

**Comment by mikkonie** [comment]
marked the task **Improve table column layout** as completed

**Comment by mikkonie** [comment]
marked the task **Force status info wrapping** as completed

**Comment by mikkonie** [comment]
mentioned in commit 71ecb35c8223a08fb856924ea046101b2e0b6ae5

**Comment by mikkonie** [comment]
mentioned in commit 83618cbb5ae31ebc16131578c7ba65ff12de314a

**Comment by mikkonie** [comment]
marked the task **Display empty Your Zones card** as completed

**Comment by mikkonie** [comment]
Done.

**Comment by mikkonie** [comment]
mentioned in commit 6ce17f2b8ecc67e195fe142761711d16b02b44db
