### ISSUE TITLE
Add custom PAM authentication for iRODS

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1263]
This is so we don't require an outside LDAP for SODAR/iRODS. Discussed with @holtgrewe earlier today.

Requires also writing a custom PAM module for iRODS, a task which will probably go to the related docker repo.

For SODAR there should be a REST API endpoint to call for the login.

## Tasks

- [x] Add SODAR REST API view for auth check
- [x] Implement custom PAM module in docker-irods
- [x] Ensure local users are created in iRODS
- [ ] Test auth in irods-docker

**Comment by mikkonie** [comment]
Example PAM module from Manuel:

[pam_multi_ldap.py](https://gitlab.cubi.bihealth.org/CUBI_Engineering/CUBI_Data_Mgmt/sodar/uploads/73af1880870716b31d613853b0a796b3/pam_multi_ldap.py)

**Comment by mikkonie** [comment]
mentioned in commit 0a67ba6d39b177c4172c46dcb49dce0ce4790f8a

**Comment by mikkonie** [comment]
marked the task **Add SODAR REST API view for auth check** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure local users are created in iRODS** as completed

**Comment by mikkonie** [comment]
marked the task **Implement custom PAM module in docker-irods** as completed

**Comment by mikkonie** [comment]
Haven't managed to test this in irods-docker yet because the SSL setup is weird. However, with similar requests sent locally and in tests I can verify this works as expected, so considering it done from the SODAR side.
