### ISSUE TITLE
Upgrade to django-sodar-core v0.10.6

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1272]
Once it's tagged.

## Tasks

- [x] Upgrade depdendency
- [x] Add timeline in `LOGGING_APPS`
- [x] Add profiling to config
- [x] Do #1276
- [x] Do #1277
- [x] Ensure #1270 has been fixed
- [x] Add additional email info in user profile docs
- [ ] Update user profile screenshot in manual once deployed with RC

**Comment by mikkonie** [comment]
marked the task **Upgrade depdendency** as completed

**Comment by mikkonie** [comment]
marked the task **Add timeline in `LOGGING_APPS`** as completed

**Comment by mikkonie** [comment]
marked the task **Add profiling to config** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure #1270 has been fixed** as completed

**Comment by mikkonie** [comment]
marked the task **Do #1277** as completed

**Comment by mikkonie** [comment]
marked the task **Add additional email info in user profile docs** as completed

**Comment by mikkonie** [comment]
mentioned in commit db6cc8b27771e81bafb929f2b4c071cd5bb1ff87

**Comment by mikkonie** [comment]
marked the task **Do #1276** as completed

**Comment by mikkonie** [comment]
Updated to WIP version, will test in production. If all appears OK, I'll finalize the release and update to the final version.

**Comment by mikkonie** [comment]
mentioned in commit 32e672fbb94ab30763deca2c5db70b1a20b2b447

**Comment by mikkonie** [comment]
Done.
