### ISSUE TITLE
Increase landing zone status message length and improve displaying

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1308]
Landing zone messages should be made more readable.

## Spec

- Support line breaks in status message
    * Assert proper rendering in UI
- Allow for longer message length
- ~~Ensure longer messages work in timeline event status updates~~
    * Yes, it's also a `TextField`
- Truncate long messages but enable viewing full message
    * Expand message in list
    * Retrieve expanded data with a separate Ajax view
- Prevent redundant updates
    * These break the expanded status info fields and are otherwise wasteful
    * See #2126

## Tasks

- [x] Add line break support
- [x] Enable longer status length
- [x] Ensure longer length is OK in timeline event status updates
- [x] Enable truncating and viewing full versions
- [x] Handle redundant updates (#2126)
- [x] Update tests
- [x] Update documentation

**Comment by mikkonie** [comment]
Done.
