### ISSUE TITLE
Upgrade all vue app dependencies to latest version

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1330]
Updating the prior task to fit the current situation.

## Tasks

- [ ] Upgrade to Vue v3 IF feasible (#994)
- [ ] Upgrade to ag-grid-vue3 (needed for vue 3)
- [x] Upgrade deprecated packages (see below)
- [x] Upgrade packages to the latest versions we can
- [x] Upgrade minimum Node version (v12 exits LTS in April)

## Known Issues

- Updated `webpack-dev-server` requires a configuration change detailed [here](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md?plain=1#L261)

This *will* be breaking and may require a bunch of work, so postponing it until a major milestone.

**Comment by mikkonie** [comment]
mentioned in commit 69732b8c1cfacb0623c39dd2c256bbd1bbb545a9

**Comment by mikkonie** [comment]
I first upgraded the basic dependencies which could be upgraded without breakages. This includes some security updates. Will try the potentially dangerous stuff in a separate commit.

**Comment by mikkonie** [comment]
Deprecated packages:

```
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
```

Another output from `npm outdated`:

```
@babel/core                 7.16.7  7.17.5       7.17.5  samplesheets
@vue/cli-plugin-babel       4.5.15  4.5.15        5.0.1  samplesheets
@vue/cli-plugin-eslint      4.5.15  4.5.15        5.0.1  samplesheets
@vue/cli-plugin-router      4.5.15  4.5.15        5.0.1  samplesheets
@vue/cli-plugin-unit-jest   4.5.15  4.5.15        5.0.1  samplesheets
@vue/cli-service            4.5.15  4.5.15        5.0.1  samplesheets
@vue/test-utils              1.2.1   1.2.1  2.0.0-rc.17  samplesheets
core-js                     3.20.2  3.21.1       3.21.1  samplesheets
eslint                      7.32.0  7.32.0        8.9.0  samplesheets
eslint-plugin-promise        5.2.0   5.2.0        6.0.0  samplesheets
eslint-plugin-standard       4.1.0   4.1.0        5.0.0  samplesheets
eslint-plugin-vue           7.20.0  7.20.0        8.5.0  samplesheets
vue                         2.6.14  2.6.14       3.2.31  samplesheets
vue-router                   3.5.3   3.5.3       4.0.12  samplesheets

```

**Comment by mikkonie** [comment]
mentioned in commit 8c25e8f0d73720389f25251b6e71e02d379a014e

**Comment by mikkonie** [comment]
mentioned in commit 51c7a391bf1a9241cf8f7cc69004753db4f53805

**Comment by mikkonie** [comment]
I briefly tested this yesterday and the Vue 3 upgrade might have to wait for later. It seems to be very breaking for multiple dependencies and with quick experimentation, I wasn't able to make ag-grid-vue3 work..

**Comment by mikkonie** [comment]
Done. Not upgrading to Vue 3 at this time, as it will be a very much breaking upgrade and certain dependencies aren't even available for it yet.
