### ISSUE TITLE
Add Django setting and usage for iRODS FQDN

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1349]
We need this now that we're running iRODS in a docker-compose environment in deployment.

## Tasks

- [x] Add Django setting
- [x] Use in client environment generation
- [x] Use in irodsinfo status display

**Comment by mikkonie** [comment]
marked the task **Add Django setting** as completed

**Comment by mikkonie** [comment]
marked the task **Use in client environment generation** as completed

**Comment by mikkonie** [comment]
marked the task **Use in irodsinfo status display** as completed

**Comment by mikkonie** [comment]
mentioned in commit eb32152e51cdbc238cc9c575ace0da867dab9972

**Comment by mikkonie** [comment]
Done.

**Comment by mikkonie** [comment]
mentioned in commit 6f6034cb3ff269413face8e845e69b54e02b1c95
