### ISSUE TITLE
Link manual to RTD, remove local manual building

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1358]
Now that the manual is in RTD, should update links on the site as well as the readme. If possible, should link to the correct tag automatically.

## Tasks

- [x] Replace links on site
- [x] Use release/dev tag in linking if feasible
- [x] Replace link(s) in README
- [x] Stop building local version in deployment

**Comment by mikkonie** [comment]
mentioned in commit 6efdff4b5e42892c1fa413277597c9b5431776d7

**Comment by mikkonie** [comment]
marked the task **Stop building local version in deployment** as completed

**Comment by mikkonie** [comment]
marked the task **Replace links on site** as completed

**Comment by mikkonie** [comment]
marked the task **Use release/dev tag in linking if feasible** as completed

**Comment by mikkonie** [comment]
mentioned in commit 15712409756ca1e9b84d7cc46025d5e3bd31cc1a

**Comment by mikkonie** [comment]
marked the task **Replace link(s) in README** as completed

**Comment by mikkonie** [comment]
Done.
