### ISSUE TITLE
Samplesheets: Upgrade to ag-grid v27

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1370]
First, good news: this upgrade doesn't seem to require any breaking changes or node dependencies.

Then, bad news: some deprecated stuff needs to be fixed. Namely:

```
AG Grid: As of v27, the property cellRendererFramework is deprecated. The property cellRenderer can now be used for JavaScript AND Framework Components.
```

```
ag-grid-community.cjs.js?7fb8:17810 AG Grid: As of v27, the property headerComponentFramework is deprecated. The property headerComponent can now be used for JavaScript AND Framework Components.
```

```
AG Grid: As of v27, registering components via grid property frameworkComponents is deprecated. Instead register both JavaScript AND Framework Components via the components property.
```

Adding this as a separate ticket from #1369 just in case it will turn out to be nasty work. For now, will attempt in current minor milestone, because we've fallen behind in our ag-grid version.

## Tasks

- [x] Upgrade packages
- [x] Ensure app works
- [x] Ensure tests run
- [x] Update `cellRendererFramework` calls
- [x] Update `frameworkComponents` calls
- [x] Update `headerComponentFramework` calls

**Comment by mikkonie** [comment]
marked the task **Upgrade packages** as completed

**Comment by mikkonie** [comment]
marked the task **Update `frameworkComponents` calls** as completed

**Comment by mikkonie** [comment]
marked the task **Update `frameworkComponents` calls** as incomplete

**Comment by mikkonie** [comment]
marked the task **Update `frameworkComponents` calls** as completed

**Comment by mikkonie** [comment]
Updating the `frameworkComponents` setup was straightforward. Alas, the other two create problems.

~~Switching from `headerComponentFramework` to `headerComponent` produces the following error:~~

Fixed! Turns out I'm stupid.

**Comment by mikkonie** [comment]
~~Replacing `cellRendererFramework` with `cellRenderer` causes the following crash:~~

Also fixed. Just needed to declare all renderers in the app components.

**Comment by mikkonie** [comment]
mentioned in commit 9af67f459b8b16c22dff58b5e0594e23724b84c8

**Comment by mikkonie** [comment]
marked the task **Ensure app works** as completed

**Comment by mikkonie** [comment]
marked the task **Update `cellRendererFramework` calls** as completed

**Comment by mikkonie** [comment]
marked the task **Update `headerComponentFramework` calls** as completed

**Comment by mikkonie** [comment]
I've no reached a point where the app seems to work 100%, but tests fail. Need to figure out how to provide the components to all tests.

**Comment by mikkonie** [comment]
mentioned in commit bc0c01b60fb8191c23f241ca6b9372eb0b8be27f

**Comment by mikkonie** [comment]
Tests fixed! Looks like I was stupid again.

**Comment by mikkonie** [comment]
marked the task **Ensure tests run** as completed

**Comment by mikkonie** [comment]
mentioned in commit 3825c4e2c2e55de018a1d0cf49f95786484b2a95

**Comment by mikkonie** [comment]
mentioned in commit 0e140509aa3d5b036bb6efdbe5682d75cbfe6b6e

**Comment by mikkonie** [comment]
Done.
