### ISSUE TITLE
Samplesheets: Improve search item layout

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1373]
While recording demo video material, I noticed some not-so-niceties in the samplesheets search items.

## Tasks

- [x] Remove redundant study column from file results
- [x] Ensure responsive modifications work with the aforementioned change
- [x] Rename assay column in file results to "Assay" as there can only be one

**Comment by mikkonie** [comment]
marked the task **Remove redundant study column from file results** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure responsive modifications work with the aforementioned change** as completed

**Comment by mikkonie** [comment]
marked the task **Rename assay column in file results to "Assay" as there can only be one** as completed

**Comment by mikkonie** [comment]
mentioned in commit d98c3c8f4e56259013e3fefa677df5506550b199

**Comment by mikkonie** [comment]
Done.
