### ISSUE TITLE
Refactor old SODAR Taskflow code

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1397]
Adding refactoring issues here while I work on #691.

## Tasks

- [x] Update flow arguments
- [x] Replace SODAR API with internal calls instead of API requests
- [x] Replace `_uuid` object members and similar in flow parameters with actual objects
- [x] Replace `get_project_path()`, `get_landing_zone_path()` and `get_sample_path()` calls with `irodsbackend.api` equivalents
- [x] Replace `TASKFLOW_IRODS_PROJECT_ROOT` with call to `irodsbackend.api`
- [x] Move `get_project_group_name()` into `irodsbackend.api`?
- [x] Move samplesheets and landingzones specific tasks into respective apps?
- [x] Set up async submit with Celery
- [x] Ensure all input for each flow is correct
- [x] Refactor `synctaskflow`
- [x] Remove redundant `targets` parameter
- [x] Remove unused `role_sync_delete_all` flow
- [x] Ensure logging from flows works properly
- [x] ~~Replace `request_mode` with `async_mode`~~ This is fine
- [x] Ensure timeline events are correctly handled
- [x] Remove `use_taskflow()`
- [x] ~~Move base taskflow test classes to separate module(s) inside taskflowbackend?~~ This is ok for now
- [x] Refactor modules and APIs
- [x] ~~Simplify timeline event status updating?~~ This seems ok
- [x] Handle `NOT CREATED` status for landing zones on flow building crash

**Comment by mikkonie** [comment]
marked the task **Update flow arguments** as completed

**Comment by mikkonie** [comment]
mentioned in commit 8331400115b3b5f57d9736999d075391e1b31141

**Comment by mikkonie** [comment]
marked the task **Replace `_uuid` object members and similar in flow parameters with actual objects** as completed

**Comment by mikkonie** [comment]
marked the task **Replace `get_project_path()`, `get_landing_zone_path()` and `get_sample_path()` calls with `irodsbackend.api` equivalents** as completed

**Comment by mikkonie** [comment]
marked the task **~~Evaluate and potentially remove `TASKFLOW_TARGETS`~~ Still needed for e.g. `synctaskflow`** as completed

**Comment by mikkonie** [comment]
marked the task **Move `get_project_group_name()` into `irodsbackend.api`?** as completed

**Comment by mikkonie** [comment]
mentioned in commit 872c2ce341ca177b387cf22c41c0c832afc357ad

**Comment by mikkonie** [comment]
marked the task **Replace SODAR API with internal calls instead of API requests** as completed

**Comment by mikkonie** [comment]
marked the task **Replace `TASKFLOW_IRODS_PROJECT_ROOT` with call to `irodsbackend.api`** as completed

**Comment by mikkonie** [comment]
marked the task **Move samplesheets and landingzones specific tasks into respective apps?** as completed

**Comment by mikkonie** [comment]
mentioned in commit 68c4c05dff97110b1513b54cd4cc2841e0dc63fe

**Comment by mikkonie** [comment]
mentioned in commit c481825a5345cfc67c933c3868ab27ea254e69b4

**Comment by mikkonie** [comment]
mentioned in commit 91733fa5b8ac2a8ef2e47c845ad9de2aed500bac

**Comment by mikkonie** [comment]
mentioned in commit 5e3a1913b4d3bc28de71993adad9644dbb009358

**Comment by mikkonie** [comment]
marked the task **Set up async submit with Celery** as completed

**Comment by mikkonie** [comment]
mentioned in commit 8a62dc7c89b11a59a182cf75e0f2d17020c53005

**Comment by mikkonie** [comment]
marked the task **Ensure logging from flows works properly** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure logging from flows works properly** as incomplete

**Comment by mikkonie** [comment]
mentioned in commit ad612d22b3993dd718f1ea9a312ae034f162c858

**Comment by mikkonie** [comment]
mentioned in commit 018561a04bd3e790f4762f7c991a78cb9b9580a1

**Comment by mikkonie** [comment]
marked the task **Ensure all input for each flow is correct** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure logging from flows works properly** as completed

**Comment by mikkonie** [comment]
marked the task **Ensure timeline events are correctly handled** as completed

**Comment by mikkonie** [comment]
mentioned in commit af7b7d637059e0d8ef06c1d6d1f64c1862d3d672

**Comment by mikkonie** [comment]
mentioned in commit 56944ee357206c4815bf4c6e9f2508abb90dff18

**Comment by mikkonie** [comment]
mentioned in commit c1110f803794210c541e3e1dfdc2ab0cc721681f

**Comment by mikkonie** [comment]
Done, to be merged.
