### ISSUE TITLE
Add host restriction support for iRODS access tickets

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1439]
Especially once doing #804, we'll most likely need to set host restrictions to tickets to make sure that e.g. only the desired site can access the data, such as a specific Kiosc instance. 

**Update 2025-04**: Now this is even more important, as we have introduced OIDC support and are deploying semi-public instances.

## Spec

- Add host restriction handling in `IrodsAPI`
    * Example: `self._send_request(irods, 'TICKET_ADMIN_AN', 'mod', ticket._ticket, 'add', 'host', host)`
        + I think, to be tested
- Add ticket modification support in `IrodsAPI`
- Add host field for `IrodsAccessTicket` model
- Add `PROJECT` scope app setting for default host restrictions for tickets
    * Not much effort needed, adds a lot in terms of usability
    * ~~**TBD:** Or, should we take this value from the project IP allow list instead?~~
        + I spoke with users and the conclusion is: no, these should be separate
- Add optional host restriction field to ticket UI views and form
    * Should support multiple hosts separated by e.g. newline
    * Initial value should be the project setting value, of course
- Add ticket addition/removal to iRODS ticket creation
    * Should also support ticket update in case hosts are replaced or removed
- Add optional host restriction in ticket REST API create/update views
    * Non-breaking API change for samplesheets API v1.1
    * Have this fail if attempting to use field with API v1.0
- Update list UI to display restricted hosts
    * Badge layout similar to new landing zone list
- Update tests to ensure host restrcitions are properly set and work
- Update UI and API docs
- Ref
    * [iRODS iticket docs](https://docs.irods.org/4.3.3/icommands/tickets/)

## Tasks

- [x] Add hosts handling in IrodsAPI
- [x] Add hosts field in model
- [x] Add ticket updating in IrodsAPI
- [x] Add hosts field handling in create/update UI views and form
- [x] Add hosts field handling in REST API
- [x] Add Django setting for default allowed hosts
- [x] Add project app setting for default allowed hosts
- [x] Update list UI
- [x] Update tests
- [x] Update docs

**Comment by mikkonie** [comment]
Done.
