### ISSUE TITLE
Set up SHEETS_EXTERNAL_LINK_LABELS via config file

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1477]
We should remove the hardcoded CUBI-specific values and get this from env in deployment. DEFAULT_EXTERNAL_LINK_LABELS should only contain generic examples.

The issue is nicely providing JSON via our playbooks. Will link some resources kindly provided by Manuel below.

**UPDATE:** After some consideration and internal discussion, I've realized that these labels can easily become quite big and not reasonable to place under env variables. Hence I'm going with an optional JSON file provided via a config directory during deployment.

## Tasks

- [x] Set up label loading via file
- [x] Move file loading from Django settings
- [x] Add tests for file loading
- [x] Ensure tests run correctly in local dev and ci
- [x] Update docs

**Comment by mikkonie** [comment]
Related Ansible resources:

- https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html
- https://stackoverflow.com/a/22978594/84349

**Comment by mikkonie** [comment]
Another way to do this: https://stackoverflow.com/questions/24003880/ansible-set-variable-to-file-content

However, the very good question of "why not just use a config file" has been raised. Will sleep over this and think of the best solution.

**Comment by mikkonie** [comment]
Done.
