### ISSUE TITLE
Disable validate/move controls in landing zone UI if project is locked by taskflow

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1512]
A long-standing illogicality is that we allow actions in the landingzones UI which will then be refused due to the project being locked by taskflow.

After implementing #2048 and #2146, this would be logical and trivial to do.

## Spec

- Disable "Validate and Move" link if project is locked
- Disable "Validate" link if project is locked
    * This will be reverted once we do #1850, but should be applied initially
- Add client-side updating to `landingzones.js`

## Tasks

- [x] Add server-side update
- [x] Add client-side update
- [x] Add/update tests
- [x] Ensure documentation is up-to-date

**Comment by mikkonie** [comment]
I'm doing project locking changes in v1.1, this would also go well with those. Tagging for the milestone, will update the spec.

**Comment by mikkonie** [comment]
Done.
