### ISSUE TITLE
Add study app tests with appropriate sample sheets

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1523]
Need to generate ISA-Tabs with appropriate configuration (if not yet there) and test the plugin methods.

## Tasks

- [x] Add sample sheets where applicable
- [x] Test `germline` plugin methods
- [x] Test `cancer` plugin methods

**Comment by mikkonie** [comment]
Done, to be merged into dev.
