### ISSUE TITLE
Optimize get_pedigree_file_path() use in germline study app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1525]
This was already improved quite a bit in #1506, but is still inefficient. In some cases, this could be replaced by using the existing study app cache item itself. Alas, for IGV session files this doesn't work, as it includes files not listed in the cache item. Unless we update the cache item itself..

Should look into refactoring this, or deleting it altogether.

The issue is related to #1509 which is the biggest bottleneck at this point anyway, so these should be done simultaneously.

**Update 2026-03:** I received reports that in a specific project in production, IGV session generation started timing out. It's time to look into this again.

I was able to reproduce the reported problem and found that generating the IGV session file indeed takes a long time. When downloading directly from SODAR, it finishes after a several minutes, but I guess IGV has a shorter timeout threshold.

The project in question has a single large-ish study (~1500 sources), germline configuration and has filled the family ID column. There is a relatively large amount of files, ~120k for the entire study.

Running tests directly on the real files in production Django shell, I discovered two bottlenecks:

1. We query for all data objects for the study within `germline.utils.get_pedigree_file_path()`.
    * This is fine in itself, but to prepare the IGV file, we call `get_pedigree_file_path()` multiple times: once for BAM, once for VCF and once for BAM files for each family member!
    * This is obviously a huge (not to mention embarrassing) bug.
1. The data object query within `get_pedigree_file_path()` itself is quite slow.
    * With 120k files this is to be expected, but IMHO it should not be quite this slow
    * There have been some fairly recent changes to `IrodsAPI`, including a refactoring of `get_objs_recursively()` in January. Perhaps I have messed something up?
    * [See IrodsAPI history here](https://github.com/bihealth/sodar-server/commits/1.2.6/irodsbackend/api.py).
    * Environmental factors can't be ruled out at the time of writing either: perhaps the iRODS iCAT server is not performing as usual?

The 1st issue should be easy to handle: query for all study objects once, pass optional object list to `get_pedigree_file_path()`. This should definitely go to the v1.2.7 hotfix release.

The 2nd one I'm not sure about at the time of writing, but I will take a look. The most important thing is to get past the timeouts in production.

## Spec

- Modify `get_pedigree_file_path()` to accept optional pre-queried object list
- Pre-query for study objects in `germline.views.IGVSessionFileRenderView.get()`
    * Provide object list to helper
- Look into `IrodsAPI.get_objects()` and related methods for potential issues
    * Fix if something obvious is found
- Test, test, test

## Tasks

- [x] Modify `get_pedigree_file_path()`
- [x] Add pre-query `IGVSessionFileRenderView`
- [x] Update germline IGV tests
- [ ] ~~Look into `IrodsAPI`~~ See #2437

**Comment by mikkonie** [comment]
Mental note: Django shell script to test out the optimization with real data in prod:

```
import time
from projectroles.plugins import PluginAPI
from samplesheets.studyapps.germline.utils import get_pedigree_file_path
from samplesheets.models import GenericMaterial
from samplesheets.rendering import SampleSheetTableBuilder

plugin_api = PluginAPI()
table_builder = SampleSheetTableBuilder()
source_name = 'XXXYYY'
m = GenericMaterial.objects.get(name=source_name)  # Provided the ID is unique on the site ;)
study_tables = table_builder.get_study_tables(m.study)

def get_path_timed(file_type, material, study_tables):
    t_start = time.time()
    p = get_pedigree_file_path(file_type, material, study_tables)
    print(f'{time.time() - t_start:.1f}s')
    return p

p = get_path_timed('bam', m, study_tables)
p = get_path_timed('vcf', m, study_tables)
```

**Comment by mikkonie** [comment]
So, last night, lying awake stressed by this issue, I was thinking "wait, why don't I actually retrieve the file paths from the study shortcut cache?" I do that for the shortcut links modal and that should be the exact same information, right?

I wrote in the original issue description:

> In some cases, this could be replaced by using the existing study app cache item itself. Alas, for IGV session files this doesn't work, as it includes files not listed in the cache item. Unless we update the cache item itself..

..but maybe that's outdated info, because the shorcuts show the same BAM/CRAM and VCF files we add into the generated IGV session file, right?

Are there some cases where we need files **not** present in the cache? I must double check.

See `get_shortcut_links()`, `StudyLinksAjaxView`.

In the worst case scenario, I'll go with this iRODS query optimization fix for now and open a new issue for improving study shortcut caching. In the best case scenario, I'll have near-instant IGV session file generation for germline studies.

**NOTE:** Even if I can successfully use the cache, the query fix is valid, as we may fall back on that if the cache item is not present. Exactly like we do in `get_shortcut_links()`..

Continuing this in #1524.

**Comment by mikkonie** [comment]
Since the immediate problem has been fixed, I'm closing this issue. For further related development, see #1524 and #2437.
