### ISSUE TITLE
Add admin functionality to reset landing zone state

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1534]
Occasionally we get some network errors which mess things up for transfers and may leave the landing zone in an undesireable state. While I'm working to eliminate these, it's probably not feasible to 100% avoid these for all possible problems, especially cases where network issues are the source.

These landing zones can be reset to a working state through some shell and irods commands, but it would be best to have a simple UI feature to do that.

## Spec

- Add permission for zone reset with access for superuser only
- Add `restrict_colls` saving into `LandingZone` model
    * Needs to be checked by flow, could technically be done from reading the timeline event but that's backwards and kludgy
    * **Update:** We also should add `create_colls` in the model, otherwise this is not very logical
- Add mixin & view for admin users in the landing zone app to reset zone state
- Logic should check whether an active celery process for the zone is running
    * If found, refuse to continue
- Add flow to do the following:
    * Ensure user access to landing zone
    * Set landing zone status to `ACTIVE`
    * Set appropriate status message
    * Send alert and email to zone owner if notifications are enabled
- Also add a management command for the same feature

It would also be nice if we could somehow automatically fix stale files which remain locked in iRODS, but I'm not sure if that is actually possible.

## Tasks

- [x] Add permission for landing zones 
- [x] ~~Add storing of `restrict_colls` in `LandingZone` model~~ see #2325
- [x] ~~Add storing of `create_colls` in `LandingZone` model~~ see #2325
- [x] Add taskflow to update access and status
- [x] Update `BaseLandingZoneStatusTask` to handle new flow
- [x] Add taskflow tests
- [x] Add mixin with flow triggering functionality
- [x] Add view
- [x] Add view tests
- [x] Add permission tests
- [x] Add UI controls
- [x] Add/update UI tests
- [x] Add management command
- [x] Add management command tests
- [x] Remove redundant `restrict_colls` arg from `submit_create()`
- [x] ~~Ensure proper API handling of `restrict_colls`~~ see #2325
- [x] Document

**Comment by mikkonie** [comment]
This has been raised again and it's not too much work, so I'm squeezing it into v1.2.0 before tagging the release.

**Comment by mikkonie** [comment]
Done. Phew. That took quite a bit of yak shaving.
