### ISSUE TITLE
Study shortcuts not correctly created for bih_cancer configuration

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1554]
I'm observing a case in production where study table shortcuts are not correctly created for a specific project using the `bih_cancer` configuration. By initial glance the sample sheets appear correct, so it is possible this is a bug.

I need to reproduce this locally and debug.

## Details

- Project has one study with multiple assays
- BAM and VCF files are available in multiple assays (but not 1st assay)
- Assay row links are correctly enabled in each assay
- The cancer study `update_cache()` saves the shortcut cache item data as `{'bam': {}, 'vcf': {}}`
- `get_study_libraries()` returns nothing
- `get_samples()` fails if samples do not follow the naming convention of `{SOURCE_NAME]-{X}`
    * ..but even after renaming the sample in question, this fails. Looking into it more..
- Within `get_shortcut_column()`, `_source_files_exist()` again assumes the specific sample name pattern
    * This should be fixable in a manner similar to `get_samples()`

## Tasks

- [x] Fix usage of `get_samples()` (also see #1557)
- [x] Fix `_source_files_exist()`
- [x] Unify `*_name` and `*_id` conventions in code
- [x] Ensure new approach works with different cancer studies
- [ ] ~~Add/update tests as needed~~
- [x] Update docs as needed

**Comment by mikkonie** [comment]
Done, however I had to postpone adding new tests for special naming conventions. See #556 for that.
