### ISSUE TITLE
Add samplesheets project archival support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1572]
Requires the implementation of bihealth/sodar-core#369.

We need to support the archived mode for projects in the samplesheets app.

Estimate with current spec would be <=1d.

## Spec

- Disable the following sample sheet modifications if project is archived
    * Sheet import/replacing
    * Sheet editing
    * Sheet config editing
    * Sheet version restoring
    * iRODS file requests
- **TBD:** Exceptions: these should probably still be allowed
    * Access ticket generation
    * Cache updating (as the result of this may change depending on SODAR implementation)
- In the future, add implementation of the `ProjectModifyAPIMixin` hook to e.g. move data into some archive
    * If I understood correctly, we are not doing this in the initial implementation

## Tasks

- [x] Add logic for archived access restriction
- [x] Add and update tests
- [x] Ensure cache updating is allowed for archived projects
- [x] Add/update UI tests
- [x] Update docs

**Comment by mikkonie** [comment]
Done.
