### ISSUE TITLE
Add landingzones project archival support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1573]
Requires the implementation of bihealth/sodar-core#369.

Support for project archival also needs to be added for the landingzones app.

IMHO we should initially keep it simple: If there still are active landing zones when archiving the project, the user should still be able to access them and delete them. Just creation of new zones and moving of existing ones should be disabled.

In the future we could add some more sophisticated logic here if needed. But this will at least require us implementing #804 and get rid of long-term LZ abuse before that.

Time estimate with current spec: <1d.

## Spec

- If project is archived, disable the following functionality in UI and API:
    * Creating new landing zones
    * Moving landing zones
- Add UI element to the zone list to note of behaviour when project is archived

## Tasks

- [x] Implement logic for project archival
- [x] Add UI elements
- [x] Add and update tests
- [x] Add missing permission & UI tests
- [x] Update docs

**Comment by mikkonie** [comment]
Done.
