### ISSUE TITLE
Landingzones: Add async updating to all activity

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#159]
Right now, the status of your active zones is periodically checked via JQuery and the UI updated accordingly.

However, there are actions related to zone activity which are not currently asynchronously updated and for matter of logic and consistency they should be :)

I'm postponing these until a post-0.3 version so we can roll out the critical functionality ASAP.

**TODO**
* [ ] Allow clearing inactive zones directly in the list via Ajax
* [ ] Add/remove zones with access to user as they become available or are removed
* [ ] If when we implement #57, also do the above for other users' zones where access is granted

**Comment by mikkonie** [comment]
This has basically now been done in #1205, closing.
