### ISSUE TITLE
Upgrade to SODAR Core v0.13.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1617]
The major SODAR Core upgrade v0.13.0 will be out soonish. SODAR v0.14 will be upgraded to run on it.

This needs to be carefully coordinated with Varfish and Kiosc, as SODAR Core v0.13 breaks a lot of things including remote sync backwards compatibility.

## Tasks

- [x] Upgrade dependencies
- [x] Figure out for advanced search problem (see core changes)
- [x] Ensure permissions are correctly maintained for the extended role inheritance
- [x] Ensure iRODS access is correctly added/removed with role inheritance
- [x] Add iRODS inherited member sync in `syncmodifyapi`
- [x] Update samplesheets and landingzones modify API calls
- [x] Update perms tests to include new inherited roles
- [ ] ~~Fix test cleanup (see comments)~~
- [x] Fix up all other potentially breaking things
- [x] Reinstall versioneer

**Comment by mikkonie** [comment]
After the most recent upgade, one of the tests fails when running all tests. If run separately in just one class, these work. Something must be going wrong with `tearDown()` and iRODS somewhere.

```
======================================================================
FAIL: test_command_multiple (irodsadmin.tests.test_commands.TestIrodsOrphans)
Test command with multiple orphans
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mikkopen/code/sodar/irodsadmin/tests/test_commands.py", line 474, in test_command_multiple
    self.assertEqual(expected, out.getvalue())
AssertionError: 'e361ce40-c845-434c-ae7d-2f33fd62ca7b;Test[306 chars]es\n' != '021072ea-8418-4c3f-8ed4-8862e97a6142;<DEL[56856 chars]es\n'
Diff is 57211 characters long. Set self.maxDiff to None to see it.
----------------------------------------------------------------------
```

**Comment by mikkonie** [comment]
I can't reproduce the aforementioned issue locally or in CI. It appears it was caused by some earlier failed test which didn't properly clean up the test iRODS server. This should be somehow improved of course, but for the time being I can let this slide.

**Comment by mikkonie** [comment]
Done.
