### ISSUE TITLE
Manual updates for v0.14.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1689]
We deploy the dev branch of SODAR in production and it links to the dev documentation on readthedocs. Alas, right now the deployment and the dev docs are a bit "out of sync", as I'm waiting for Varfish and Kiosc to catch up on the SODAR Core updates.

This is a collected issue of critical manual updates which need to be done for v0.14.0, to be merged around the time we're ready to deploy the latest dev branch in production.

Screenshots should be updated where applicable.

Separate issues for v0.14.0 manual updates should only be opened if a long spec/description or discussion is needed.

## User/Admin Docs

- [x] Full role inheritance
- [x] Finder role
- [x] SODAR Core v0.13 UI changes
- [x] Sheet table height modifications
- [x] Userprofile changes
- [x] bihealth/sodar-server#1688
- [x] Add note(s) on running `syncmodifyapi` to sync iRODS perms
- [x] Add note on automated generating of MD5 checksums in `zone_move`
- [x] Update iRODS access ticket docs
- [x] Update 7zip reference to NanaZip (Windows 11 issue with 7zip)
- [x] Ensure all screenshots are up to date
- [x] Review REST API docs
- [x] ~~**TBD:** What to do with BIH proteomics data transfer doc?~~ see bihealth/sodar-server#1745

## Dev Docs

- [x] bihealth/sodar-server#1690
- [x] bihealth/sodar-core#1293

## Misc

- [x] Do bihealth/sodar-server#1583

**Comment by mikkonie** [comment]
Done.
