### ISSUE TITLE
Refactor IrodsDataRequest model, API views and tests

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1706]
There are some issues.

## Tasks

- [x] Update model tests
- [x] Move model helper into `samplesheets.tests.test_models.IrodsDataRequestMixin`
- [x] Remove redundant `IRODS_DATA_REQUEST_STATUS_CHOICES` constant and usage
- [x] Add constants for action and status
- [x] Expect `action` field value in upper case
- [x] Add model-level validation for `action` and `status` fields
- [x] Refactor view tests
- [x] Refactor permission tests
- [x] Fix permissions on modifications with archived projects
- [x] Update non-standard API view responses
- [x] Remove repetition from form/API validation
- [x] Rename views
- [x] Use `request_knox()` in API view tests
- [x] Add missing `IrodsDataRequestListAPIView` permission tests
- [x] Add missing `IrodsDataRequestListAPIView` view tests
- [x] Add missing UI view permission tests
- [x] Fix permission issues in UI views
- [x] Refactor Ajax view tests, add missing tests
- [x] Remove all "bla" stuff
- [x] Do #1734 
- [x] Do #1735
- [x] Do #1736
- [x] Do #1737

**Comment by mikkonie** [comment]
Done. Phew!
