### ISSUE TITLE
Refactor taskflowbackend base test classes

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1722]
These base classes are convoluted, contain a lot of repetition and don't work perfectly for all cases.

## Tasks

- [x] Move TaskflowAPI.cleanup() to tests
- [x] Move duplicated `setUp()` and `tearDown()` to `TaskflowTestMixin`
- [x] Rename API project/assignment creation helpers for clarity
- [x] Refactor base classes and usage for relevant use cases
- [x] Do #1718

**Comment by mikkonie** [comment]
Done, to be merged.
