### ISSUE TITLE
Move IrodsObjectListAjaxView and related JQuery into landingzones app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1730]
The iRODS object list view is nowadays only used in the landingzones app, as samplesheets lists come from the vue app.

To simplify things, we should move the object list view into landingzones and make it landingzones specific.

We definitely will have to merge #1702 before working on this.

## Spec

- Move view to `landingzones.views_ajax`
    * Rename appropriately
- Move related JQuery to `landingzones.js`
- Remove references to `irodsShowChecksumCol` (no longer relevant)
- Move tests into `landingzones`

## Tasks

- [x] Create new view in landingzones
- [x] Create new JQuery in landingzones
- [x] Move and update tests
- [x] Remove old view and JQuery
- [x] Remove old tests
- [ ] ~~Refactor remaining old irodsbackend Ajax views~~ See #2145
- [x] Remove `irodsShowChecksumCol` references
- [x] Ensure documentation is up to date

**Comment by mikkonie** [comment]
Done.
