### ISSUE TITLE
Refactor permission tests to match samplesheets conventions

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1739]
With #1706 done, the permission tests in the samplesheets app are now the new yardstick regarding permission test conventions.

The other apps should be similarly refactored. This is not urgent, but something which would be nice to have for the current release.

## Spec

- Split tests per view class
- Follow consistent method naming and docstrings
- Set URL in class to avoid repetition where applicable
- Use `cleanup_method` and `setUp()` set up things, remove unnecessary iteration within actual tests

## Tasks

- [x] Update tests in `irodsbackend`
- [x] Update tests in `irodsinfo`
- [x] Update tests in `landingzones`
- [x] Update tests in `ontologyaccess`

**Comment by mikkonie** [comment]
Done.
