### ISSUE TITLE
Upgrade to django-sodar-core v0.13.2

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1775]
One somewhat serious bug fix already, so I believe this will be tagged alongside SODAR v0.14.0.

## Tasks

- [x] Upgrade to final version
- [x] Use `sodar-btn-submit-once` in relevant forms
- [x] Update version number mention in release notes

**Comment by mikkonie** [comment]
Done.
