### ISSUE TITLE
Disable enforced formatting for study titles and table headers

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1776]
## Problem
Currently SODAR auto-formats strings in multiple places in a not always ideal way:

- Underscores are replaced with spaces
- Words are forced to start with a capital letter and not contain any more i.e. This Style.

This is done for study names, assay names, and all samplesheet column headers. Very often, this style does not fit the content we put in these text fields. For example:

- scRNA-seq in assay names gets converted to Scrna-seq
- KRAS and pERK1/2 in Characteristics fields are converted to Kras and Perk1/2

## Suggested action
One of the following
- Stop auto-formatting in these places
- Tone down to just replacing underscores
- Give a user setting to disable auto-formatting

**Comment by mikkonie** [comment]
Related to #576. I probably will not stop as that makes everything look terrible, but toning down or adding a user setting for this are good ideas.

**Comment by sellth** [comment]
I would argue the opposite, auto-formatting makes many things look terrible. The platform name is written cBioPortal.

![grafik](https://github.com/bihealth/sodar-server/assets/29800411/d59f9bbb-49a4-475d-b77f-25c1c8ac90b9)

**Comment by mziehm** [comment]
As a user. I second the point of @sellth that the current auto-formatting lead to ugly formatting. As further examples Qc instead of QC or Pcr instead of PCR. 
I would argue that the responsibility for the correct capitalization should be with the definition.
Underscores I personally find a bit more tricky as they are common used internal naming a space replacement and then often displayed best with space. But options would be in any case great.

**Comment by mikkonie** [comment]
I've looked into this and I'm in favour of disabling "auto-formatting" for study titles and table headers. Makes more sense to have things consistent with the original sample sheets. Not to mention for cases where dumb capitalization of things simply doesn't work.

For assays this will not change within this context, as the ISA-Tab standard only uses the file name as the assay identifier. We should definitely enable setting a SODAR specific assay title as suggested in #1782, but that's a different issue.

As for "replacing underscores with spaces", the only place I can immediately find we do this is generating the assay display name from the file name. This will not change because, well, see above. If there are other places where this happens which I'm missing and are not desireable, please create specific tickets about them and we'll see whether that is valid behaviour or not.

**NOTE:** Care must be taken in ensuring all internal table header name comparisons work. I usually do my best to make string comparisons case insensitive in such cases, but mistakes happen. I need to be especially sure that we are checking for `header['name']` and not `header['value']`. This also makes `header['value']` redundant in the current conversion, but I'm keeping it around for now in case there is need to display an alternative formatting for header names in the future.

**NOTE 2:** To update table headers with existing sample sheets without user interaction, an admin needs to run the `syncstudytables` management command after deploying the release to rebuild the table cache. This must be reflected in the docs.

If there is demand for it, I can later add a user setting for selecing how these are displayed. But that's a different ticket.

## Tasks

- [x] Disable study title altering
- [x] Disable table header altering
- [x] Ensure table header comparisons still work
- [x] Ensure sheet config and display config work
- [x] Update tests as needed
- [x] Update docs

**Comment by mikkonie** [comment]
Done.
