### ISSUE TITLE
Add assay details modal

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1827]
### Problem
`Study Assay Measurement Type` and `Study Assay Technology Type` are mandatory ontology-qualified fields in all ISA-tabs which hold information about the assay performed. SODAR currently uses these fields to choose an appropriate assay plugin, but doesn't display this information in any way.

### Solution
Show these properties beneath or in context of each assay header, including hyperlinks to the ontology term sources.

For clarification, this assay header:
![image](https://github.com/bihealth/sodar-server/assets/29800411/4b2a1225-e67c-45e3-9135-e0839b7e6454)

**Comment by mikkonie** [comment]
I agree that this information should be easily visible to the user. I'll think about a nice way to present it in the UI. It could be just text, or we could e.g. replace the plugin link with a link to open a modal with measurement type, technology type AND plugin info. Maybe some other assay specific info could go there too.

I consider this a nice "low hanging fruit" feature we can implement in v1.0 before going forward with the full app rewrite, as rewriting this would be quick and trivial.

**Comment by mikkonie** [comment]
## Spec

- ~~Add Ajax view to provide assay details~~
    * Scratch that: we can simply add the details to `SheetContextAjaxView`
        + Only a few additional items to what we already have
- Add the following info:
    * Measurement type
    * Technology type
    * Comments
    * Plugin name (plugin title is already there)
    * **TBD:** More?
- Add modal to display assay info in Vue app
- (Bonus: also look into adding assay info into Overview if/where viable, but probably this is for another issue)

## Tasks

- [x] Add assay data to `SheetContextAjaxView`
- [x] Update view tests
- [x] Add modal
- [x] Add modal tests
- [ ] ~~Update documentation~~ To be updated in #2265

**Comment by mikkonie** [comment]
Done. Study support to be added in #2265.
