### ISSUE TITLE
Remove project lock requirement when running landing_zone_move flow with validate_only

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1850]
Running the `landing_zone_move` taskflow with `validate_only` does not do anything in the sample repository, nor does it even lock write access to the landing zone. Still, it triggers the project lock.

We should change this so that if the `validate_only` arg is set, we don't require project lock. This would enable e.g. running multiple validations parallel.

If we allow validating an infinite amount of zones simultaneously, it creates a vector for DOSing the iRODS and SODAR servers, either maliciously or by mistake. Hence a limit should be introduced. That will be handled as a separate ticket, as I first want to get the unlimited version up for testing in staging.

Also related: #2148 

## Spec

- Remove lock requirement from taskflow
- Ensure UI and REST API views are appropriately accessible
- Disable UI element disabling if validate-only is active
- Ensure documentation is up-to-date

## Tasks

- [x] Remove taskflow lock requirement
- [x] Update taskflow tests
- [x] Update UI view tests
- [x] Update REST API view tests
- [x] Remove UI element disabling
- [x] Update UI tests
- [x] Update documentation

**Comment by mikkonie** [comment]
Done.
