### ISSUE TITLE
Add CRAM file support for IGV in study plugins

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1908]
There is a request from @holtgrewe for adding .cram file support for IGV sessions. Spec forthcoming. If it's not too major, I'll get this in v0.14.2.

## Spec

- Update study app methods to search for both .bam and .cram
    * **TODO:** List related methods here
- Ensure .cram files get inserted into generated IGV sessions
- Ensure .cram files are also properly found for study cache
- **TBD:** Extend `SHEETS_IGV_OMIT_BAM` and `igv_omit_bam` setting functionality to CRAM files?
    * If so, update GUI labels and setting spec
- Update GUI labels to reflect CRAM support
- Add tests
    * Test link retrieval
    * Test cache
    * Test IGV generation
    * Remember to test with both .bam and .cram (dummy) files, including combinations of both
- Update documentation

## Tasks

- [x] Update `cancer` plugin and tests
- [x] Update `germline` plugin and tests
- [x] Update labels for BAM omit settings
- [x] ~~Update GUI if needed~~ Seems to be OK
- [x] Update documentation regarding BAM support
- [x] Update major changes doc with migrate info

**Comment by holtgrewe** [comment]
OK, here we go. For IGV it does not matter whether the file is a BAM or CRAM file so we can place CRAM everywhere we place BAM.

The current logic to identify the BAM file for a single sample/library

1. in the library directory, look for all files ending in `.bam`
2. sort this list lexicographically
3. use the last found one

This logic needs to be changed to (1) reads "in the library directory, look for all files ending in `.bam` or `.cram`.

That's all we need.

**Comment by mikkonie** [comment]
Done.
