### ISSUE TITLE
Grant owner and delegate iRODS read/write access to all project zones

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1934]
This has been raised by @Nicolai-vKuegelgen. It is slightly illogical that an owner or delegate can see the landing zones of others in the UI and perform actions such as moving and deleting, but they do not have actual iRODS access to the zone collection.

I don't really see a harm in providing owners and delegates with this currently missing access.

Implementation-wise this would be relatively simple: just add owners and delegates to where we enable/disable zone access in `landing_zone_create` and `landing_zone_move` taskflows.

Tagging this for the next major version, unless I hear objections from anyone. I'll write a full spec after the Easter holidays.

**Update 2025-03**: Ok I think my Easter holidays may have been slightly extended :P Spec below.

Also, to keep this consistent the access should also be added/revoked when owner/delegate access is modified in project. This will require a bit more effort but should not be too bad.

Requires #2109.

## Spec

- Add project owner/delegate group management (see #2109)
- Enforce creation and population of owner group on zone creation
- Add write access to project owners and delegates in `landing_zone_create`
- Ensure access is correctly modified for all users in `landing_zone_move`

## Tasks

- [x] Add ensuring owner group creation in `ZoneModifyMixin`, test
- [x] Update user access modification in `landing_zone_create`
- [x] Update `landing_zone_create` flow tests
- [x] Update `landing_zone_create` view tests
- [x] Update user access modification in `landing_zone_move`
- [x] Update `landing_zone_move` flow tests
- [x] Update `landing_zone_move` view tests
- [x] Document

**Comment by mikkonie** [comment]
Done.
