### ISSUE TITLE
Update REST API versioning for SODAR Core v1.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1936]
To be done after/during #1922.

REST API versioning will be changed in SODAR Core v1.0.0, see bihealth/sodar-core#1278.

These changes need to be also done for SODAR apps. This will sadly be a breaking change, as deprecating the old versioning and providing a temporary workaround would IMHO not be worth the effort.

API calls without strict versioning will continue to work as usual, as URLs are not affected. My hunch is that most clients haven't even bothered to set up versioning, but I could be wrong..

## Tasks

- [x] Add versioning for samplesheets
- [x] Add versioning for landingzones
- [x] Add versioning for irodsinfo
- [x] Update API docs for each app
- [ ] ~~Mention breaking change in release notes~~ To be done in #1991
- [ ] ~~Remove `SODAR_API_*` settings (exception: `SODAR_API_DEFAULT_HOST`)~~ Can't, see bihealth/sodar-core#1495
- [x] Update `release_cleanup.md` regarding versioning

**Comment by mikkonie** [comment]
Done.
