### ISSUE TITLE
Add opt-out settings for email notifications

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1939]
Following bihealth/sodar-core#1417, we should also add similar opt-out settings for landing zone and samplesheet activities.

## Tasks

- [x] Add opt-out for iRODS data request accept/reject
- [x] Add opt-out for landing zone owner status updates
- [x] Update tests (see also #1916)
- [x] Update user profile and major changes docs

**Comment by mikkonie** [comment]
Done.
