### ISSUE TITLE
Add django-axes support

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1976]
**UPDATE:** Depends on bihealth/sodar-core#1750, postponed until upgrading to SODAR Core v1.3.

This would be useful once we integrate OIDC from SODAR Core v1.0 and look into deploying public instances. Thanks to @holtgrewe for the heads up.

- [Github repo](https://github.com/jazzband/django-axes)
- [Installation docs](https://django-axes.readthedocs.io/en/latest/2_installation.html)

Looking at the installation docs, this shouldn't require any hardcoded changes to SODAR Core, so I'm opening the issue here directly. However, if some issues regarding SODAR Core changes do come up, I'll add a separate ticket to that repo and integrate it there as well.

**Update:** Hold the phone! It seems there are some issues which need solving and, sadly, also postponing this to SODAR v1.3.

## Issues

- ~~Supporting django-axes for DRF REST API views requires [app-level signal binding](https://django-axes.readthedocs.io/en/latest/6_integration.html#integration-with-django-rest-framework)~~
    * Moot point, since token authentication is not currently supported by django-axes.
    * Token-using REST API views will simply be omitted for now
- ~~A great number of UI tests fail in CI. However, in dev they work fine. I should figure out what's different.~~
    * Solution found in bihealth/sodar-core#1750
- ~~Apparently, django-auth-ldap is not directly supported and I was unable to quickly locate documnentation for supporting it.~~
    * LDAP logins, at least the way we have implemented them, work just fine out of the box.
- We need to specifically ensure this works for views where we fall back to basic auth
    * `irodsbackend.views.BasicAuthView`
    * Study app views

## Tasks

- [x] Add and test setup in SODAR Core
- [x] Add dependency and config setup
- [x] Add relevant env vars and default values
- [x] Update `FallbackToAuthBasicMiddleware` to support django-axes
- [x] Add tests for irodsbackend `BasicAuthView`
- [x] Add tests for study app views
- [x] Disable logging in tests
- [x] Document

**Comment by mikkonie** [comment]
Most of the issues regarding django-axes were solved in bihealth/sodar-core#1750. After doing #2334, support can be nicely added. I will axe (see what I did there?) the existing non-working work branch in favour of a new one.

**Comment by mikkonie** [comment]
Done.
