### ISSUE TITLE
Cleanup and prepare v1.0.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1991]
## Minor Tasks

- [x] Add major changes note on Postgres dependency requirements
- [x] Add major changes note on iRODS requirements
- [x] Add major changes note on breaking REST API versioning changes
- [x] Cleanup `samplesheets.utils.write_excel_table()`
- [x] Cleanup nested list definitions in `TestIrodsDataRequestAcceptBatchView`
- [x] Add mention of `isatemplates` app in `README` and elsewhere where missing
- [x] Cleanup `pep_ms` assay plugin class docstring
- [x] Add `--use-pep517` to python requirement installs (#1977)
- [x] Add running `npm audit fix` into `release_cleanup.md`
- [x] Fix `SampleSheetExportException` reference in `import_isa()` docstring
- [x] Clarify v1.0 iRODS/PostgreSQL requirements in admin upgrade docs
- [x] Ensure v1.0 iRODS/PostgreSQL requirements are properly documented elsewhere in manual
- [x] Remove "Beta" as default `SITE_SUBTITLE`
- [x] Make cache update Django messages conform to convention
- [x] Clarify minimum supported `sodar-docker-compose` and image versions in admin docs
- [x] Add breaking changes note to `README`
- [x] Add note on iRODS configuration on upgrade (see bihealth/sodar-docker-compose#81)
- [x] Add `SHEETS_API_FILE_EXISTS_RESTRICT` in `SHEETS_INFO_SETTINGS`

## Issues to Add in CHANGELOG

- [x] Add #1922
- [x] Add #1978 (as part of Python upgrade)
- [x] Add #1936
- [x] Add #1994
- [x] Add #1951

## Release Checklist

- [x] Run `npm audit fix`
- [x] Review code style and cleanup
- [x] Review and update docs entries
- [x] Ensure REST API versions are up to date and documented
- [x] Run `npx update-browserslist-db@latest` for Vue app
- [x] Update Vue app version with `npm version`
- [x] Update version in CHANGELOG and SODAR Release Notes doc
- [x] Update version in docs conf.py
- [x] Ensure docs can be built without errors
- [x] Ensure `generateschema` runs without errors or warnings (until in CI)

## Notes

N/A

**Comment by mikkonie** [comment]
Done.
