### ISSUE TITLE
Add progress information in landing zone status

### ISSUE THREAD

**Issue by january3** [bihealth/sodar-server#2024]
### Problem

Validation and moving of LZs can sometimes take quite a lot of time. It would be good to know, in terms of orders of magnitude, how much more time this is going to take (minutes? hours? days?)

### Solution

A progress indicator in the LZ view, optimally with a time estimate should provide a user feedback (e.g. 15/127 files validated in 2 hours, or: 15/127 validated, approximately 2 hours remaining).

**Comment by mikkonie** [comment]
Moving this into the SODAR server repo, as this software does not concern that part.

**Comment by mikkonie** [comment]
This is partially discussed in #1919. I agree that there should be a way to see more detailed output regarding the progress of these operations.

Time estimates are a very difficult thing though. In the end these depend on the iRODS backend file system(s) which SODAR has no knowledge of. We would need some way to gauge and store expected performance of the backend. I'm all for ideas on how to do that, not my area of expertise TBH.

**Comment by mikkonie** [comment]
This has been so widely requested that I'm getting it out of the way now. Initially it will be a simple file count progress information. We can look into calculating something of an estimate in a subsequent issue.

## Tasks

- [x] Add progress display to `BatchCalculateChecksumTask`
- [x] Add progress display to `BatchValidateChecksumsTask`
- [x] Add progress display to `BatchMoveDataObjectsTask`
- [x] Update tests as appropriate
- [x] Update docs

**Comment by mikkonie** [comment]
Done.
