### ISSUE TITLE
Improve API return data for landing_zone_create with missing project iRODS collections

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2036]
Reported by @Nicolai-vKuegelgen. Currently the landingzones API returns `HTTP 400` if attempting to run `landing_zone_create` on a project for which iRODS collections have not been created.

The request itself is not technically invalid in this case. Hence, instead of `400` we should return `503` with a descriptive error message.

This is in line with the changes I recently made in #1847 and should be trivial to implement, so this would fit nicely in v1.0.0.

This is technically a breaking change, so I'll have to be sure to document it as such.

## Tasks

- [x] Update view to return `503` instead of `400`
- [x] Ensure descriptive error message
- [x] Update tests
- [x] Update documentation (including release notes)

**Comment by mikkonie** [comment]
Done. The message itself looked fine though.
