### ISSUE TITLE
Add optional checksum retrieval to IrodsAPI.get_objects()

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2038]
It would be very useful for e.g. `ProjectIrodsFileListAPIView` to also display the checksum for each data object.

~~For the sake of completeness, I believe this should be returned as a list of replica/checksum pairs, as the same file may exist in multiple replicas. Alternatively, maybe the user could supply a specific resource name..~~

**Update:** Actually no. We compare all replica checksums on landing zone validation. If they would be different at this point, something would have gone horribly wrong.

This could be done together with #1996 and #1997 as they are somewhat related.

## Tasks

- [x] Add checksum arg to `get_objects()` and relevant internal functions
- [x] Add checksum retrieval if arg is set True
- [x] Update tests
- [x] Ensure docs are up to date

**Comment by mikkonie** [comment]
Done.
