### ISSUE TITLE
Add file checksums to ProjectIrodsFileListAPIView return data

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2039]
This view should also return file checksums. See also #2038.

This is a non-breaking change but it will bump the samplesheets API version mumber by `.1`.

## Tasks

- [x] Add checksum arg to `get_objects()` call based on API version
- [x] Update default API version number to `1.1`
- [x] Set allowed API versions to `['1.0', '1.1']`
- [x] Update tests, also test for v1.0 API call
- [x] Update API view docstring and `@extend_schema`
- [x] Update samplesheets API docs
- [x] Ensure `make spectacular` still works

**Comment by mikkonie** [comment]
Done.
