### ISSUE TITLE
Change non-standard return data format of ProjectIrodsFileListAPIView

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2040]
The format of the return data is currently inexplicably an `irods_data` object with the actual list contained within. This goes against SODAR Core and SODAR conventions and also would make it confusing once we implement pagination (see #1996).

This is technically a breaking change, but as we can make breaking changes before introducing new versioning in v1.0, it can be done. 

Existing clients need to be updated to expect a pure list.

## Tasks

- [x] Update return data in view
- [x] Update tests
- [x] Update docstring with full description of return data
- [x] Update docs (including release notes for breaking API change)

**Comment by mikkonie** [comment]
Done.
