### ISSUE TITLE
Add "is project locked" helper and views in taskflowbackend

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2048]
While looking into #2041, I realized we should have a common "is project locked" API method for checking whether we should allow specific activity.

Logically, this should be provided in `taskflowbackend` as it controls the locking.

This will help with e.g. updating the UI of different apps regarding whether the project is currently locked or not. Also, this can be used even if we introduce new flows locking the project, or changing the locking mechanism altogether. Knowledge of the locking logic should stay 100% inside taskflowbackend, of course.

**Edit:** Forgot to write that there of course also need to be an API view for this.

Related issues: #1512, #1844, #1850

## Tasks

- [x] Add helper to `TaskflowAPI`
- [x] Add API view
- [x] Add/update tests
- [x] Update documentation

**Comment by mikkonie** [comment]
Done.
