### ISSUE TITLE
Samplesheets: Add iRODS deletion request

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#227]
In GitLab by @holtgrewe on Jun 6, 2018, 09:01

Implement iRODS data object / collection deletion request for project sample data repository.

Exact task and spec below. In the future, we should expand this with "move object/collection to X".

Notes from @mikkonie:

Initially, let's do the Taskflow request and status updating in a synchronous way. It is possible that deletion will take a long time with collections containing a large number of data objects, potentially resulting in a timeout. However, this *shouldn't* be a huge or common issue. IMHO we can improve this into async behaviour later if needed.

Regarding layout stuff, copy existing things but don't worry about it too much. I can tweak cosmetics before this is merged. Before the year 2038 I hope to find time to create that style guide..

@holtgrewe & @stolpeo, comments and questions are welcome.

## Tasks

- [x] Add `IrodsDeleteRequest` model in `samplesheets.models`
- [x] Add Ajax API views for handling requests
- [x] Add deletion flow in SODAR Taskflow (see sodar_taskflow#67)
- [x] Add view for managing delete requests
- [x] Add UI for issuing/cancelling requests in `IrodsDirModal`
- [x] Add/update tests for Django and Vue app

### Add `IrodsDataRequest` model in `samplesheets.models`

- `project`: `Project` reference
- `path`: Full path to iRODS data object or collection (unique, one request per path)
- `action`: Char field, default=`DELETE` (we'll most likely add `MOVE` at a later date)
- `target`: Char field to target path if we do a move request. Can be empty, currently not used
- `user`: User initiating the request
- `status`: Char field for request status: `ACTIVE`, `ACCEPTED`, `FAILED`
    * Can be expanded with e.g. `WORKING` if we do async operations
- `status_info`: Text field for optional information regarding current status
- `description`: Description text field (optional)
- `date_created`: Datetime
- `sodar_uuid`    

### Add Ajax API views for handling requests

- General notes
    * All modifying actions need to create timeline events
- Create/update request
    * Allowed if role != project guest
    * Validation
        * Ensure path belongs to project
        * Do **not** allow request for deleting collection for entire assay/study/project 
        * If creation/updating is done through the free text form, ensure data object / collection actually exists in the path given
            + Use irodsbackend -> session
            + Don't allow creation/update if object/collection can't be found
        * Also check as much of these as possible already in the UI to prevent unnecessary requests and handling
- Delete request
    * Allowed if role != project guest
    * Removal of request by original issuer
    * Called "Cancel" in the UI
- Accept request
    * Allowed if role == owner || delegate
    * Initiates an async SODAR Taskflow flow for deletion (more on this below)
        + Yes, it has to be async because iRODS deletion can potentially take a long time
    * Initially synchronous, expand to async later
    * **NOTE:** If requesting the deletion of a data object, also include the `*.md5` file in the list of objects to be deleted!
    * Taskflow will return with status of `ACCEPTED` or `FAILED`
        + Set request object status and status info as appropriate
        + If `ACCEPTED`, trigger project cache update before done
    * Hint: See taskflow views in landingzones to get a decent idea of how these usually work
    * Send user an email about the acceptance
    * Make sure to update timeline
- Reject request
    * Allowed if role == owner || delegate
    * Delete object on rejection
    * Send email to user about rejection
    * Make sure to update timeline!
    * Keep data object / collection
- Query for dir list with request info
    * See below for details

### Add deletion flow in SODAR Taskflow

- See separate task in sodar_taskflow (sodar_taskflow#67)

### Add view for managing delete requests

- Accessible via `Sheet Operations` dropdown
- Displayed and accessible if user role != project guest
- Implement as server-side Django views for now
    * Client side stuff actually not necessary (at least unless we switch the deletion to async)   
    * Much faster to implement and simple to test in Django..
    * ..However, adding interactive stuff like async list updating of course much easier in Vue
- Display list of delete requests
    * As owner/delegate
        + Display all active delete requests in the project
        + Display buttons for accepting/rejecting each request
        + NOTE: Yes, same actions for request created by you and others
        + When clicking accept, display confirmation dialogue before actual triggering of deletion
    * As contributor
        + Display your active delete requests in the project
        + Display button for cancelling each request
- Display basic form for adding a new request
    * Fields
        + Path (input)
        + Comment (text box, optional)
    * Should be displayed for all users who access this modal, even owners/delegates
    * This allows for easy creation of request based on path in icommands, also for collections and orphaned stuff not visible in the UI
    * Once request is created, add to the list described above (of course)
- Also allow updating user's own requests
    * Only path and descriptions should be editable

### Add UI for issuing/cancelling requests in `IrodsDirModal`
    
- Displayed if user role != project guest
    * Yes, owner/delegate must also delete by first issuing a request
- Add column with button to issue/cancel deletion request for each data object
    * User should be able to cancel their own deletion request afterwards in case of e.g. a misclick               
    * Change button appearance regarding request status
- Highlight data objects with active deletion request with e.g. strikethrough
- Query for existing requests when retrieving iRODS dir list
    * Disable issue/cancel button if requests created by another user exists for the data object
    * **NOTE:** Currently this is retrieved from an Ajax view in `irodsbackend`
    * For now, create a similar Ajax view in `samplesheets` which adds the request info

**Comment by mikkonie** [comment]
unassigned @stolpeo
