### ISSUE TITLE
Landingzones: Automated creation of expected collections

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#391]
I was thinking about the landing zone process while teaching this to Franziska and it's definitely not very intuitive now.

A very nice thing would be to, upon landing zone creation, create valid base directories for landing zone content based on the configuration and related samplesheets sub-app plugins. This will save the user trouble for creating them themselves, avoiding the possibility for typos, etc.

E.g. in a case of expecting data in libraries, the library directories would be created upon building the landing zone.

This could be optional, or we might even allow the user to select from a list for which samples/libraries/etc they wish to add data. Collections which are empty at validation phase will **not** be moved over to the sample data repository anyway, so this is mostly a clarity issue when the user is browsing their zone in iRODS.

## Tasks

- [x] Add expected collection form option
- [x] Add functionality to REST API
- [x] Implement collection gathering
- [x] Implement in SODAR Taskflow
- [x] Add tests
- [x] Update docs
