### ISSUE TITLE
Samplesheets: Render sheets using Vue.js and ag-grid

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#426]
The first step for building the new ISA editor.

Initially, just display sheets as currently, based on the throwaway sodar_isa_editor prototype.

Data should be retrieved from client side (most likely doable just by wrapping the current study table renderer in an Ajax API view).

Once done, this should also close #100 and #223. The next step will be adding simple editing of data, which will be under its own ticket.

## Tasks (to be appended as needed)
* [x] Set up ag-grid as in sodar_isa_editor
* [x] Render actual study and assay data from Django database
* [x] Render all metadata as in SODAR 0.4 (needs #441 for file links)
* [x] Add performer & date rendering (see #187)
* [x] Optimize cell rendering speed
* [x] Implement client-side study navigation
* [x] Implement Overview page as client-side
* [x] Implement other samplesheets navigation as Django links for now (import etc)
* [x] Implement filtering
* [x] Implement hiding/showing study data in assay table
* [x] Add TSV export links
* [x] Make leftmost column sticky
* [x] Set up iRODS links (#438)
* [x] Include data from study and assay apps (#436)
* [x] Redesign shortcut table to better work with different data and ag-grid (see #464)
* [x] Include `update_row()` functionality from assay apps (#441)
* [x] Add iRODS button/stats updating (pending #241)
* [x] Implement multi-cell value selection and copying from sodar_isa_editor
* [x] Implement cell expanding hover
* [x] Remove unneeded stuff from server side table-from-graph rendering
* [x] Make sure TSV exports still work after the previous step
* [x] Add HPO linking (#478)
* [x] Set up tests
* [x] Cleanup app from possibly unneeded stuff created by vue-cli
* [x] Set up production and deployment
