### ISSUE TITLE
Samplesheets: Upgrade to the latest version of altamISA

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#527]
Need to upgrade to the latest altamISA (v0.1)

## Tasks

* [x] Add parser version (#553)
* [x] Update `*Reader.from_stream()` calls
* [x] Fix crash from trying to access `unit` in a `Comment` (unit no longer present)
* [x] Parse `characteristics` and `parameter_values` as lists
* [x] Make sure rendering supports both old and new style of `characteristics` and `parameter_values`
* [x] Add fields and parsing for `headers` in all nodes (list of strings)
* [x] Add parsing of `headers` to Investigation/Study section JSONfields
* [x] Remove unused `header` field from Study and Assay
* [x] Remove `characteristic_cat` and `unit_cat` (specific to the original JSON spec)
* [x] Add field and parsing for `name_type` in Process
* [x] Add field and parsing for `first_dimension` in Process
* [x] Add fields and parsing for `second_dimension` in Process
* [x] Remove support for `scan_name` in Process
* [x] Handle `extract_label` as possible ontology reference (needs migration trickery from CharField)
* [x] Implement validation
* [x] Add field in Investigation for parser warnings (from validation) + usage
