### ISSUE TITLE
Samplesheets: Allow saving column visibility

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#539]
Adding the possibility to save your preferred column layout to #466 would be a useful thing and shouldn't be too hard to implement.

Current idea for implementation:

- User preference saving
    * User opens the modal and changes something
    * Upon closing down the modal (we already override the event handler), call an async API view to save preferences based on user and study/assay table.
    * Naturally, will have to implement a data model and a view for this
- Default column visibility
    * Also need to allow the sheet importing/creating user to define default values
    * The most simple way way to do this: for specific users (e.g. admin/owner/delegate and/or importer of the ISAtab), add a separate "save as default" button which does the job
    * Need to also add the possibility to define a default config to the data model mentioned above

## Tasks

- [x] Define plugins for user/default display config
- [x] Add config creation/updating for import/replace/delete
- [x] Add config usage in the Vue app
- [x] Add config saving from the Vue modal
- [x] Add default config saving in the Vue modal
- [x] Test everything
