### ISSUE TITLE
Samplesheets: Add initial editing

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#550]
Initial editing features. Just allowing the editing of existing fields/columns of certain types for now.

## Tasks

- [x] Implement test mode and navigation
- [x] Provide editing context data to Vue app via API view
- [x] Allow editing for specific columns (see #687)
- [x] Implement allowed values for certain columns (see #687)
- [x] Implement displaying related changes between study and assay tables
- [x] Implement saving of changed values (all relevant members of material/process for initial version)
- [x] Gray out columns not allowed to be edited
- [x] Disable potentially harmful buttons when editing of a cell is active
- [x] Disable multi-cell selection when editing is active
- [x] ~~Disable parent scrolling when popup editing is active~~ Postponed to v0.7.1 and moved to #712
- [x] Implement popup for e.g. unit values
- [x] Display error notification if saving fails
- [x] ~~Fix cell layout in Chrome (fixed for `input`, still needs to be fixed for `select`)~~ Postponed to v0.7.1, movced to #726 
- [x] Save ISAtab backup once finished editing
- [x] ~~Add tests~~ Postponed for v0.7.1, see #749.

## Temp Task Notes / Optional Stuff / TBD

- [x] "Finish editing" reloads 1st study even if another one is active when selecting it
- [x] Need to disable home/end key navigation when editing (see the numeric editor example)
- [x] Unable to input certain characters to editor (possibly due to the navigation updates above?)
- [x] ~~Move class name to `_add_top_header()` if editing (can also refactor vue.js app check)~~ Nope, better to have in field header after all
- [x] ~~Only pass UUID in the first column for each node to limit data transfers: pass to all columns in node via editor params~~ Postponed to separate task (#708)
- [x] ~~Show all columns when in edit mode regardless of data or not?~~ Showing empty columns with edit config
- [x] ~~Show empty cell instead of default-value-for-no-data when editing?~~ Nah, good like it is.
- [x] Fix assay column editing to work with JSON config
- [x] Keyboard navigation control not correctly returned once exiting custom editor
- [x] ~~**TBD:** For selectable values/units/etc, follow order in config or e.g. sort alphabetically?~~ Follow order.
- [x] Fix unit UI updating in other tables
- [x] Fix default selected value in unit UI
- [x] Improve popup layout
- [x] ~~Ontology ref support for unit~~ Will support these in v0.8
- [x] Move empty value to the top of the list in selections
- [x] Fix value updating between study/assay tables (seems to fail if selecting and initial value is empty)
- [x] Disable sorting when edit mode is enabled
- [x] Display unit selection if only one choice is available (empty is also a choice!)
