### ISSUE TITLE
Add missing samplesheets tests

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#556]
EDIT: Merging similar issues together.

* [x] Test cache creation/updating/deletion
* [ ] Ensure sheet consistency after replacement
* [ ] Ensure iRODS files consistency after replacement
* [ ] UI tests for vue app column toggling (#466)
* [ ] UI tests for iRODS dir filtering (#467)
* [ ] UI tests for table row filtering
* [x] UI tests for warning view
* [ ] Tests for ensuring column ordering in `rendering.py` (#566)
* [x] Test for the `SampleSheetIO` API and its methods/funcs
* [x] `SampleSheetISAExportView` permission & view tests
* [x] Missing API view tests
* [x] Sheet import/export extra_data in timeline events
* [ ] Missing permission tests for Ajax views (iRODS request views)
* [x] Search tests
* [ ] Cancer study app tests with identically named libraries and unconventional naming

**Comment by mikkonie** [comment]
marked the task **UI tests for warning view** as completed

**Comment by mikkonie** [comment]
mentioned in commit 5d6fa9a58ce9ac6523fce9e8ef2208615b6e565d

**Comment by mikkonie** [comment]
marked the task **Search tests** as completed
