### ISSUE TITLE
Update app settings to match django-sodar-core v0.6.2

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#569]
## Tasks
* [x] Add `user_modifiable` fields to settings definitions in project app plugins
* [x] Use `get_django_setting()` instead of `get_setting()` in templates
* [x] Make sure tests pass
