### ISSUE TITLE
Split LDAP setup similar to SODAR Core

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#608]
LDAP stuff caused issues and SODAR can also be run in local user mode, so the setup to this should be split similarly to SODAR Core (separate ldap.txt field in requirements)

## TASKS

- [x] Move LDAP requirements to `ldap.txt` like in SODAR Core
- [x] Update docs where applicable to state that if LDAP is needed, also install prerequisites from `ldap.txt`
- [ ] Update ansible playbooks?

@stolpeo: I can check the 3rd task once the rest has been done.

**Comment by mikkonie** [comment]
This has been done, closing.
