### ISSUE TITLE
Implement taskflow functionality in SODAR

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#691]
Once Taskflow has been decoupled from SODAR Core: see bihealth/sodar-core#387.

- Implement Taskflow as a backend app in SODAR
- Hook into SODAR Core project/role updating functionality via a plugin app

## Tasks

- [x] Upgrade to WIP version of SODAR Core containing new plugin API replacing taskflow calls (undefined##undefined)
- [x] Implement taskflowbackend app in SODAR
- [x] Integrate SODAR Taskflow code in taskflowbackend
- [x] Hook taskflow operations into the new API
- [x] Implement modify API revert methods
- [x] Write tests for modify API use
- [x] Fix taskflow logging not visible for non-async flows
- [x] Move tests from SODAR Taskflow and SODAR Core, update where necessary
- [x] Improve tests to assert iRODS content where not yet present
- [x] Remove redundant use of `change_plugin_status()` in tests

**Comment by mikkonie** [comment]
mentioned in issue undefined##undefined

**Comment by mikkonie** [comment]
mentioned in issue sodar_taskflow#87

**Comment by mikkonie** [comment]
mentioned in issue sodar_taskflow#94

**Comment by mikkonie** [comment]
mentioned in issue sodar_taskflow#95

**Comment by mikkonie** [comment]
mentioned in issue undefined##undefined

**Comment by mikkonie** [comment]
mentioned in commit f856d89e76805068f1800be31b6f5f785b49c35f

**Comment by mikkonie** [comment]
marked the task **Upgrade to WIP version of SODAR Core containing new plugin API replacing taskflow calls (undefined##undefined)** as completed

**Comment by mikkonie** [comment]
marked the task **Implement taskflowbackend app in SODAR** as completed

**Comment by mikkonie** [comment]
marked the task **Hook taskflow operations into the new API** as completed

**Comment by mikkonie** [comment]
mentioned in commit e25b27e2f96c1881384709c1d76e78c6080d23c7

**Comment by mikkonie** [comment]
mentioned in commit a869cb6b65c3acd72e4f6d5e0b11a711158d6e9d

**Comment by mikkonie** [comment]
mentioned in commit ab1347b5216905a7aaa339937ff16063cdf100ec

**Comment by mikkonie** [comment]
mentioned in commit 91733fa5b8ac2a8ef2e47c845ad9de2aed500bac

**Comment by mikkonie** [comment]
mentioned in commit 5e3a1913b4d3bc28de71993adad9644dbb009358

**Comment by mikkonie** [comment]
mentioned in commit c481825a5345cfc67c933c3868ab27ea254e69b4

**Comment by mikkonie** [comment]
mentioned in commit 8a62dc7c89b11a59a182cf75e0f2d17020c53005

**Comment by mikkonie** [comment]
mentioned in commit ad612d22b3993dd718f1ea9a312ae034f162c858

**Comment by mikkonie** [comment]
mentioned in commit 018561a04bd3e790f4762f7c991a78cb9b9580a1

**Comment by mikkonie** [comment]
marked the task **Integrate SODAR Taskflow code in taskflowbackend** as completed

**Comment by mikkonie** [comment]
mentioned in commit af7b7d637059e0d8ef06c1d6d1f64c1862d3d672

**Comment by mikkonie** [comment]
mentioned in commit 56944ee357206c4815bf4c6e9f2508abb90dff18

**Comment by mikkonie** [comment]
mentioned in commit 0a24cb79210a4539996ac0c33cfe35f76e97c6e2

**Comment by mikkonie** [comment]
mentioned in commit f82be8474b753df61da2c42171675e2f26e41271

**Comment by mikkonie** [comment]
mentioned in commit f5a6ee51adec86ea52a2f679bb796ef9eb588d49

**Comment by mikkonie** [comment]
Done.
