### ISSUE TITLE
Samplesheets: Add ontology support to editor

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#699]
Support for editing ontology values needs to be added. HPO terms (#688) is the major specialized use case, however technically it should be mostly similar to other ontology fields.

## Tasks

- [x] Refactor providing ontology values to UI and rendering (see #693)
- [x] Add mandatory `ontology_name` field to the `OBOFormatOntology` model (see #947)
- [x] Add basic column configuration UI
- [x] Add basic editor for value querying and inserting
- [x] Add saving of ontology data on server side
- [x] Make sure editing works for newly added rows
- [x] Implement manual entry
- [x] Warn & replace if list not allowed
- [x] Add editing of existing values
- [x] Add reordering of existing values
- [x] Add cell value copy-paste
- [x] Make sure editing works with special fields (1)
- [x] Add support for term query limiting
- [x] Add support for term query ontology ordering
- [x] Add ontology ordering UI to column config
- [x] Add flagging for unknown ontologies
- [x] Add flagging for obsolete terms
- [x] Add updating of `Investigation.ontology_source_refs`
- [x] Make sure things do not explode if e.g. an ontology is deleted from ontologyaccess
- [x] Add automatic ontology field to creating new edit configs
- [x] Add tests where applicable
- [x] Update editor help modal

## Temp Tasks

- [x] Updating edit config of an ontology field breaks rendering until reload
- [x] Ontology column config not correctly updated before reload when enabling for 1st time
- [x] Incorrect ontology list rendering for newly inserted rows before reload
- [x] Height of term select box changes if no results are returned?
- [x] ~~Do not force table refresh if cancelling out of `finishEditCallback()`~~ see (2)
- [x] Autoconfig `allow_list=True` for `HPO Terms` in `ColumnConfigModal`
- [x] Disable insert button if `insertData` is empty or term already exists
- [x] Make table column width fixed
- [x] Add spinner to denote query in progress
- [x] Rename `term_url` in Ajax view data to `accession` for consistency
- [x] Fix accidentally broken editing
- [x] Prevent manual adding/editing of invalid ontology name if limited
- [x] Allow searching through `sodarOntology` ontologies if no ontology limit is set
- [x] Add sheet ontologies from ontology source refs on column config updating
- [x] Add sheet ontologies from ontology source refs on ontology value updating
- [x] Make sure editor works with old AND new config
- [x] Disallow navigation if edit modal is open and `updated===true`
- [x] Redundant `editing` attr returned with `og_value`
- [x] Optimize query request timing (see code comments)
- [x] Remove redundant `sheetOntologies` list from UI
- [x] Edit buttons disabled if entering editor on an empty term
- [x] Crash with missing ontology name (see `i_small`)

## Notes

- (1) Special fields:
    * `extract_label`
        + See `i_small2.zip` for an example
        + Implemented as string editing for now (see #964)
    * `extra_material_type`
        + **Q:** Do we use this?    
    * `first_dimension` and `second_dimension`
        + I believe @mkuhring said we are not using these at the moment
- (2) Have to refresh even if not updating the data. Ag-grid feature?

## Planning

- Accessing ontology data
    * Import and access through the `ontologyaccess` app (#937)
- Column config
    * Enable/disable editing
    * Allow/disallow list
        + Allowed by default for HPO terms
    * Limit to 0-N ontologies
        + Ordering matters so allow reordering
    * Update `Investigation.ontology_source_refs` as ontologies are added/removed
- Editor
    * Use a modal (popup editors don&#39;t work well with scrolling)
    * Query for ontology values via ontology site app Ajax view
    * Also allow free entry
    * If unknown ontology values are received from an imported sheet, display but mark them
        + **TBD:** Also mark in cell renderer?
    * Flag obsolete terms
- Notes
    * Search for ontologies via ontology name (see #947), not SODAR UUID (in case we need to replace)

## Old Notes

This is actually a bit more complex issue than simply adding some UI component to Vue.

- What is the workflow of adding and selecting ontologies when editing a sample sheet?
- Do we define ontologies by hand or selecting them via some API?
- Do we pre-define suggested ontologies for the investigation and additional ones for fields?

Edit: discussed this in length with Manuel and Mathias. Some points

- We need to maintain flat lists of ontologies and their terms e.g. with a separate Django app
- Implement a popup editor with search through these ontologies
- Allow limiting allowed ontologies in sheet configuration
