### ISSUE TITLE
Samplesheets: Refactor column type determining

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#730]
The old style is not optimal now that we have initial editing and JSON configuration included.

## Tasks
- [x] Use JSON configuration if present, override other methods
- [x] Check/alter value in `_add_header()` and/or `_add_cell()` where applicable
    * This also helps in optimizing data size, see #708 
- [x] Update types dynamically when editing column configuration in UI, see #698
