### ISSUE TITLE
Vue app and Initial sheet editor refactoring

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#747]
Collecting stuff from here I'm omitting from v0.7.0 as they are not critical. Mostly internal cleanup stuff and refactoring.

See also #537 which is more about general code cleanup.

## Tasks

- [x] Do not save empty column arguments to sheet config
- [x] Look into refactoring cell comparator assignment so that `colType` is not needed for each cell (1)
- [x] Go through the entire `ColumnConfigModal` component and refactor where needed (2)
- [x] Move modals to a separate subdirectory to aid in browsing component files
- [x] Set up content id with a function to avoid unnecessary (and incorrect) PyCharm error complaints
- [x] Default regular expressions for integer and double are defined twice (3)
- [x] Rename ``ShortcutModal`` to ``StudyShortcutModal`` to avoid confusion with assay shortcuts
- [x] ~~`col_type` and `header_type` used interchangeably in rendering/editing~~ (4)
- [x] Return proper error messages in `SampleSheetEditAjaxView`, display in javascript console
- [x] Remove repetition from `ColumnConfigModal` OR split into multiple modals based on column type
- [ ] ~~Unify/clarify confusing naming between *header* and *column*~~ see #899 
- [x] ~~Move cell editing helper functions away from `App.vue`~~ (5)
- [x] ~~Move `headerÌnfo` from `cellEditorParams` to `headerComponentParams` (6)~~ No longer relevant
- [ ] Rename `sodar-ss-data-links-*` classes (7)
- [x] Reduce repetition in special right-pinned column definitions (`shortcutHeaderGroup` etc.)
- [ ] ~~Review and potentially unify naming conventions in data passed between server/client (e.g. `obj_cls` vs `objCls`)~~ see #2467 
- [x] Move default `fieldConfig` setup from `FieldHeaderEditRenderer` to `ColumnConfigModal`? (8)
- [ ] Do we need to update `colType` for both `cellRendererParams` and `headerComponentParams`?
- [x] Remove unneeded `colType` from cell edit data
- [x] Refactor `editContext.samples` into a dict with UUID as key
- [ ] ~~Move `obj_cls` and `uuid` into node root when calling the row insert ajax view~~ see #2468
- [ ] Pass `gridOptions` in editor params without having to always call `getGridOptionsByUuid()`?
- [x] Unify naming of `sodar-vue-*`, `sodar-ss-*` and `sodar-ss-vue-*` CSS classes (11)
- [ ] Switch to using vue-axios instead of Fetch for Ajax calls?
- [x] ~~Refactor form select items into a nice bootstrap-vue design (see [here](https://bootstrap-vue.org/docs/components/form-select))~~ or maybe not, see #1030
- [ ] Rename redundant `*Click()` event handlers for `@click` events (9)
- [ ] ~~Use VueX store for app state?~~ Using Pinia, no longer relevant
- [x] Only use `app` callback where applicable (12)
- [ ] ~~Rename `*Callback()` functions into `*Cb()` (10)~~
- [x] Move grid building helpers away from `App`
- [x] Move grids into separate components if viable
- [ ] ~~Modify `pageHeader` to receive a `params` object~~ Doesn't seem relevant anymore
- [x] Rename `editStudyConfig` to `studyEditConfig`
- [x] Remove unused(?) `row-num` and `col-num` attributes from `DataCellRenderer`?
- [x] Get rid of extra indent with `export default Vue.extend({`
- [x] Refactor edit helpers from `App` into a separate utils file (see #1036)

## Notes
- (1) Requires updating comparator when column type is changed in the editor, is this possible?
- (2) This is super complex and probably can be simplified a lot. Should do proper UI tests first.
- (3) Both in `ColumnConfigModal` and `DataCellEditor`. Should be defined once at `app` and provided to subcomponents as property/data
- (4) My bad, turns out they actually do have a very distinct functionality. Maybe the naming could still be reconsidered as it's a bit confusing..
- (5) Not a good idea actually, since these require quite a lot of data and methods from `App`. Tried it and the end result just looked more confusing, needing tons of callbacks etc.
- (6) This info is usable for more than just the editor!
- (7) No longer exclusively used for links, also for row editing column
- (8) ..unless there's an actual reason for it being there? Can't figure one out right now. Also, this should be cleaned up and refactored.
- (9) ..unless actually required to be differentiented from another handler on the same event
- (10) Note: must be `Cb` not `CB`, as the latter will appear as `c-b` in template props which looks silly
- (11) Brevity is key, so should just simplify into `sodar-ss-*`.
- (12) Turns out this is actually a rather OK pattern (at least until we maybe switch to VueX) as it can be easily stubbed. Should not shy from providing `app` as a prop *where relevant*. Need to rollback some changes I did to the opposite.

**Comment by mikkonie** [comment]
mentioned in commit 724bbe72ce4507d983347e0874c84eea252ec896

**Comment by mikkonie** [comment]
marked the task **Do not save empty column arguments to sheet config** as completed

**Comment by mikkonie** [comment]
mentioned in commit 274589bdcaaff4f175c69ded4b1beded7abcdfd2

**Comment by mikkonie** [comment]
marked the task **Look into refactoring cell comparator assignment so that `colType` is not needed for each cell (1)** as completed

**Comment by mikkonie** [comment]
marked the task **Look into refactoring cell comparator assignment so that `colType` is not needed for each cell (1)** as incomplete

**Comment by mikkonie** [comment]
marked the task **Move modals to a separate subdirectory to aid in browsing component files** as completed

**Comment by mikkonie** [comment]
mentioned in commit 79a8ae2d9b8a1f984865fcf6a46a28f3028623bf

**Comment by mikkonie** [comment]
marked the task **Set up content id with a function to avoid unnecessary (and incorrect) PyCharm error complaints** as completed

**Comment by mikkonie** [comment]
marked the task **Remove repetition from `ColumnConfigModal` OR split into multiple modals based on column type** as completed

**Comment by mikkonie** [comment]
marked the task **Refactor `editContext.samples` into a dict with UUID as key** as completed

**Comment by mikkonie** [comment]
marked the task **~~Move cell editing helper functions away from `App.vue`~~ (5)** as completed

**Comment by mikkonie** [comment]
marked the task **Rename ``ShortcutModal`` to ``StudyShortcutModal`` to avoid confusion with assay shortcuts** as completed

**Comment by mikkonie** [comment]
mentioned in commit 4ebe1b2b2ee1bb6a4d541977b21b61fadd850633

**Comment by mikkonie** [comment]
mentioned in commit 4605ddd874990a32ddd6ca9881afb51042dc7649

**Comment by mikkonie** [comment]
marked the task **Move grid building helpers away from `App`** as completed

**Comment by mikkonie** [comment]
mentioned in commit e1db3cb884ac234829962d3c18a3a3ab46a2a510

**Comment by mikkonie** [comment]
mentioned in commit fe65d0abc976a0626a158a9e9467c3e034e825f2

**Comment by mikkonie** [comment]
marked the task **Move grids into separate components if viable** as completed

**Comment by mikkonie** [comment]
mentioned in commit ec747175c562565d60cdccbba44c89ad239c3064

**Comment by mikkonie** [comment]
mentioned in commit 26912b65e2cc568fce09836bb66888fc52dec5a3

**Comment by mikkonie** [comment]
mentioned in commit 26c541680d115edc997558087c9a7e5abd912fc0

**Comment by mikkonie** [comment]
mentioned in commit df5b7168d0f8c385e46994803c0597e5f9b78489

**Comment by mikkonie** [comment]
mentioned in commit 5052f9179ab922857c63c7696888f0d8349d3b03

**Comment by mikkonie** [comment]
mentioned in commit 7ef90df4be77e186403621bf71c5b065925ed560

**Comment by mikkonie** [comment]
mentioned in commit db74ec22ddc48bbc83e052996150d75ba25477a4

**Comment by mikkonie** [comment]
mentioned in commit 835b18b2341202ab71c59536e6a97055f6d73be5

**Comment by mikkonie** [comment]
marked the task **Go through the entire `ColumnConfigModal` component and refactor where needed (2)** as completed

**Comment by mikkonie** [comment]
marked the task **Unify naming of `sodar-vue-*`, `sodar-ss-*` and `sodar-ss-vue-*` CSS classes (11)** as completed

**Comment by mikkonie** [comment]
marked the task **Get rid of extra indent with `export default Vue.extend({`** as completed

**Comment by mikkonie** [comment]
marked the task **Only use `app` callback where applicable (12)** as completed

**Comment by mikkonie** [comment]
marked the task **~~Refactor form select items into a nice bootstrap-vue design (see [here](https://bootstrap-vue.org/docs/components/form-select))~~ or maybe not, see #1030** as completed

**Comment by mikkonie** [comment]
mentioned in commit 09d9016ce680aa2b6de0c62403cfa55b6746d535

**Comment by mikkonie** [comment]
mentioned in commit c1af1a3676522c7cd2050d62c6e536ee5be7b01c
