### ISSUE TITLE
Samplesheets: Add tests for vue app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#750]
Been given the OK to do this so let&#39;s do it. Also refactor where appropriate (see #747)

## Tasks

- [x] Set up basic testing framework
- [x] Do simple initial tests as proof-of-concept
- [x] Disable warnings
- [x] Add testing to CI
- [x] Add unit tests for `AssayShortcutCard`
- [x] Add unit tests for `IrodsButtons`
- [x] Add unit tests for `IrodsStatsBadge`
- [x] Add unit tests for `ListRow`
- [x] Add unit tests for `NotifyBadge`
- [x] Add unit tests for `Overview`
- [x] Add unit tests for `PageHeader`
- [x] Add unit tests for `Warnings`
- [x] Add unit tests for `SheetTableHeader`
- [x] Add unit tests for `SheetTable`
- [x] Add unit tests for `ColumnConfigModal`
- [x] Add unit tests for `ColumnToggleModal`
- [x] Add unit tests for `EditorHelpModal`
- [x] Add unit tests for `IrodsDirModal`
- [x] Add unit tests for `OntologyEditModal`
- [x] Add unit tests for `StudyShortcutModal`
- [x] Add unit tests for `WinExportModal`
- [x] Add unit tests for `DataCellRenderer`
- [x] Add unit tests for `FieldHeaderEditRenderer`
- [x] ~~Add unit tests for `IrodsButtonsRenderer`~~ see #1034
- [x] Add unit tests for `RowEditRenderer`
- [x] ~~Add unit tests for `StudyShortcutsRenderer`~~ see #1034
- [x] Add unit tests for `DataCellEditor`
- [x] Add unit tests for `ObjectSelectEditor`
- [x] Add unit tests for `OntologyEditor`
- [x] Add unit tests for `gridUtils.js`
- [x] ~~Add complete stubbing of `App.vue`~~ It's as complete as needed
- [x] Remove redundant python UI tests from `TestProjectSheetsView`
- [x] Make sure `disabled` attributes (not classes!) are tested properly
- [x] Fix commented out test in `NotifyBadge.spec.js`
- [x] ~~AFTER initial tests have been done, refactor editing helpers into utility class (see #747)~~ Adding as separate ticket

(List to be amended with specific functionalities to be tested)

## Help and Resources

- Basic Resources
    * [Basic unit test examples](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html)
    * [Common tips](https://vue-test-utils.vuejs.org/guides/#common-tips)
    * [Ag-grid vue testing docs](https://www.ag-grid.com/javascript-grid-testing-vue/)
- [Mocking callback functions](https://jestjs.io/docs/en/mock-function-api#mockfnmockimplementationfn)
- Mocking Ajax calls (may require switching to axios, see #747)
    * https://vue-test-utils.vuejs.org/guides/testing-async-components.html
    * https://github.com/Belar/hapi-vue/blob/master/template/test/unit/specs/App.spec.js
    * https://stackoverflow.com/questions/53792274/how-can-i-test-an-api-call-in-vuejs-using-jest
- How to test Bootstrap-vue modals
    * Set `:static="true"` on modal
    * Use `async ()` on test case
    * **After modal.show():** call **both** helpers from `utils.js` (taken from official bootstrap-vue tests)
        + `await waitNT(wrapper.vm)`
        + `await waitRAF()`
    * Use `await` on any DOM changing operation (obviously)
    * Examples also said to use `attachTo: createContainer()` in `mount()`, but this doesn't seem to affect anything. Legacy stuff?
- Best way to test for `disabled="disabled"`:
    * True: `expect(wrapper.find('#id').attributes().disabled).toBe('disabled')`
    * False: `expect(wrapper.find('#id').attributes().disabled).toBe(undefined)`
    * `*.props().disabled` MAY work if target is a vue component with the `disabled` property.. but not always!
    * See #1017 
- How to update `select option` value
    * `await wrapper.find('#your-select').findAll('option').at(x).setSelected()`
    * **Note:** Will **not** work with bootstrap-vue select!
- Bootstrap-vue testing
    * Poor person's method of testing `@input`:
        + `wrapper.setData({ vModel: 'value' })`
        + `wrapper.find('#your-field').vm.$emit('input')`
- Beware the use of `.not` in your tests
    * If used on e.g. an attribute of an element, this may return `true` if the element itself does not exist at all!
    * Better check for the exact value of the attribute/property instead

## WIP/TODO/WTF

- Coverage?
- Disable warnings globally? ([see here](https://medium.com/swlh/6-ways-to-run-jest-test-cases-silently-67d2fead8c11))
- `AgGridDragSelect` might be somewhat tricky to test, need to mock the entire app first
- Why does this work: `jest.spyOn(wrapper.props().editorHelpModal, 'showModal')`
    * ..but this doesn't? `jest.spyOn(wrapper.props().app, 'handleStudyNavigation')`
    * (Init/mocking of these methods is identical)
    * Probably something to do with deep `mount()` and actually initing the `editorHelpModal` component.. but since the actual method is mocked this shouldn't matter?!
    * **Update:** Since I know have the `getAppStub()` helper, I can simply spy on the app object method instead. Problem solved!
