### ISSUE TITLE
Sheet editor roadmap

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#771]
This is an ongoing issue to track incremental development for the sample sheet editor. Will tag separate tags as appropriate.

## Tasks

- [x] Editing of simple values for selected columns (#550)
- [x] Column configuration (#698)
- [x] Restoring/browsing saved sample sheet versions (#662)
- [x] Editing of columns beyond initially supported ones (dates, contact..)
- [x] Editing of ontology values and unit ontology references (also lists of ontologies, e.g. HPO terms)
- [x] Editing name fields **(TBD)**
- [ ] Direct paste of value without entering editor
- [ ] Multi-cell clipboard paste
- [ ] Adding/removing/renaming columns **(TBD)**
- [x] Adding/removing rows **(TBD)**
- [ ] Editing investigation/study/assay meta-data **(TBD)**
- [ ] Adding/removing studies/assays **(TBD)**
- [ ] Creating a new sheet from scratch
- [ ] Creating a new sheet from default configurations
- [ ] Full screen display/editing (#654)
- [ ] Combo box for select editing
- [ ] Tour help for editing (#729)
