### ISSUE TITLE
Cleanup for v0.7.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#772]
Minor tasks here, to be squashed in a single commit.

## Tasks

- [x] Use `bg-success` in the finish editing notification
- [x] Move modals (see #747)
- [x] Remove commented out and debug stuff in vue app
- [x] Improve `sheet_edit` timeline event description
- [x] Split timeline event to start and stop editing events
- [x] Set `user_modifiable=False` in the `sheet_config` project setting
- [x] Rewrite tooltip for column configuration button
