### ISSUE TITLE
Cleanup for v0.7.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#790]
Minor tasks to be squashed into one cleanup commit go here.

## Tasks

- [x] Fix "Importing investigation" log message in `samplesheets.io`
- [x] Tweak parser version logging message in `samplesheets.io`
- [x] Fix double quotes in sentry setup
- [x] Add missing tests for landing zone creation API view
- [x] Add versioning headers to landingzones API tests
- [x] ~~Document landingzones API~~ Postponing to v0.7.1 once the auth updates from SODAR Core are in
