### ISSUE TITLE
Cleanup and Refactoring for v0.7.1

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#828]
Minor tasks here.

## Tasks

- [x] Ensure `redirect()` is used instead of `HttpResponseRedirect()` (undefined##undefined)
- [x] Refactor `LandingZoneStatusRetrieveAjaxView` to use base SODAR Core classes
- [x] Make sure no API view tests are still using legacy test classes/methods (e.g. `TestInvestigationRetrieveAPIView`)
- [x] Update API view docstrings to match SODAR Core (see #819)
- [x] Add API view documentation to docs (see #819)
- [x] Move taskflow API view tests to dedicated files similar to SODAR Core
- [x] Remove workaround for #844
