### ISSUE TITLE
Samplesheets: Add row inserting

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#834]
What it says on the tin.

## Tasks

- [x] Inserting a new row into a table
- [x] Modification of editability per node
- [x] Update referral to existing nodes when changing name
- [x] Support for protocol editing (#871)
- [x] Handle process creation/selection (name is currently hidden for most cases?)
- [x] Enable creation/referral of next node when previous one is filled
- [x] Add filling out empty/default data for new cells
- [x] Do #881 (needed for saving row data)
- [x] Saving of new row data
- [x] Update UUIDs and row number in UI after successful save
- [x] Allow empty material names for non-sources/samples (1) (#898)
- [x] Set up default protocol for columns automatically for sheet edit config (#879)
- [x] Implement process collapsing
- [x] Implement event handler and confirm dialog for unsaved row (5)
- [x] Tests (where applicable)
- [x] Documentation
- [x] ~~Before deploying, wipe out all sheet edit configs from the server (to be regenerated)~~ see #904

## Temp Issues / TODO

- [x] Column config broken for assay table beyond study columns
- [x] Index-based lookup broken in `ColumnToggleModal`
- [x] Process field editing enabled in new row even if protocol is empty
- [x] Selecting sample in assay breaks edit button logic
- [x] Editing/config broken for first process in assay
- [x] Certain material names render with `text-muted` class after filling (for files this is OK, verify)
- [x] Fix `editable` modification (broken, requires reloading at the moment)
- [x] Fix every column showing up as "editable" in `ColumnToggleModal`
- [x] Provide `item_type` from UI to Ajax view
- [x] Handle `name_type` for processes
- [x] Fix UI behaviour on changing name/protocol on an already initialized node
- [x] Fix process/material node activating if default protocol is set
- [x] `headers` not included for last material in assay
- [x] ~~Only provide `obj_cls` once per node when calling the ajax view~~ Moved to #747
- [x] New sample gets created when choosing an existing sample for the assay table
- [x] Do not provide headers where we refer to existing nodes
- [x] Add new row info in `handleFinishEditing()`
- [x] Redundant cell info is passed for sample in assay
- [x] Update `editable` and `cellClass` when finalizing row save
- [x] Update sample list if adding new samples
- [x] Update sample list on sample rename
- [x] Update new row controls after successful insert
- [x] Add confirmation for (new) row deletion
- [x] Fix #885 and do #886 
- [x] Fix sorting of columns with units
- [x] Do not autofill default values on process nodes before selecting protocol
- [x] Entering `library_name` does not enable editing of the next node
- [x] Make sure leftover units are removed (see Nfn-Orgstrat-Cov19)
- [x] Cell alignment class not updated in `DataCellRenderer` for new row when changing column config without reloading page
- [x] Repeating cell value propagation is broken now because of course it is
- [x] Handle leftover `performer` (see Nfn-Orgstrat-Cov19, 1st assay)
- [x] Add wait wheel and disable row buttons while saving (for sheets with a lot of columns)
- [x] Handle Labeled Extract Name (`header_type=null` for name)
- [x] Process name column configuring not working correctly (most likely to missing header_type)
- [x] Process name editing for new row not allowed unless enabled from column config (related to the aforementioned issue)
- [x] ~~Modifying name/protocol column configuration breaks editability for existing new row~~ Added a temporary workaround for now, see #897
- [x] Handle process name saving
- [x] Undefined `headerComponentParams` error in specific column (see Nfn-Orgstrat-Cov19, 1st assay, 11th node, performer)
- [x] Add ajax view test for updating process name
- [x] Handle next node enabling in processes without protocol (process name = first cell, see 2nd raw file node in `i_small`)
- [x] Empty choices possibly appearing in assay sample selection? (see Row Insert Test project)
- [x] Revert button layout back to the original design
- [x] Remove unused `defNodeIdx` and `defFieldIdx`
- [x] Allow referring to an existing node on a new row after entering initial node ID
- [x] Do not allow selecting empty value in `ObjectSelectEditor`
- [x] Fix partial row cell filling for assay tables in `RowEditRenderer` (2)
- [x] Optimize `sampleColId` search for `RowEditRenderer`
- [x] Handle OR disable editing of sample fields in new assay row
- [x] Fix handling of `Label` in `Labeled Extract Name` (see #900)
- [x] Fix node UUID updating in assay table
- [x] Protocol name should be enabled for new row node, even if it's not the first cell in node
- [x] Controls no longer re-enabled if row saving fails in server side (3)
- [x] Identical "saving" controls may be visible in multiple rows if saving several rows between reloads (4)
- [x] Test collapsing with multiple ISAtabs to make sure it works as intended in all cases
- [x] Renaming a sample not reflected in the assay table sample selection editor
- [x] Remove redundant console output or print in debug only

## Notes

- (1) To support partial data, see e.g. REDACTED
- (2) Setting a default protocol value does not correctly set `newInit` in subsequent cells
- (3) Probably `newRow` is not correctly checked/set somewhere?
- (4) This hasn't happened for a while so either it's a very random bug or my recent changes to the control enabling/disabling code fixed it
- (5) See [here](https://stackoverflow.com/questions/56550164/how-can-i-mimic-onbeforeunload-in-a-vue-js-2-application)[](url)
