### ISSUE TITLE
Upgrade site to django-sodar-core v0.8.0

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#835]
Starting with a WIP version, should make sure all changes play nicely here.

## Tasks

- [x] Upgrade to current dev commit (2020-04-01), fix/refactor where appropriate
- [x] Update dependencies
- [x] Upgrade black and reformat
- [x] Remember to update site settings if/where needed
- [x] Switch to using base API classes from SODAR Core (see #800)
- [x] Use base form classes where applicable
- [x] Make sure irodsbackend Ajax views work properly after updates
- [x] Update base template
- [x] Test Bootstrap 4.4 once upgraded in SODAR Core
- [x] Update JS/CSS includes for JQuery, Bootstrap and Popper in Ansible playbooks
- [x] Once the final SODAR Core release is frozen, test once more

## Issues / Temp Tasks

- [x] Dropdowns in Vue.js app look different (see if #836 helps)
