### ISSUE TITLE
Samplesheets: Add API view for sample sheet ISAtab export

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#849]
Currently only accessible for UI views, thanks to @holtgrewe for pointing this out.

## Tasks

- [x] Set up generic mixin for the export function
- [x] Use generic mixin in the UI view
- [x] Add API view also using the generic mixin
- [x] Add tests for API view
- [x] Document
