### ISSUE TITLE
Samplesheets: Enable renaming process/material

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#852]
Needed for #834. This is closely tied to the row adding functionality, as node name in the table (naturally) how the user refers to a specific ISA model node in the backend. "It's not Excel (tm)"

## Spec

- In the first iteration this, we will only allow **renaming existing nodes**
- Specific actions
    * Change `name` in UI and model
    * Change `unique_name` in model and related arcs (see altamISA)
- Requirements / Constraints
    * Propagate change to related rows in UI (already done by the app for all fields which get changed)
    * Check for dupe
       + Do not allow dupes
       + If editing a study column in an assay table, also check for dupes in the study
- For other activities related to changing node name (changing reference / creating new ones), see #855 
- Initially, let's not care about breaking iRODS paths (there could be a warning in the UI if the node name is found as the iRODS collection for the row)

## Tasks

- [x] Add enabling/disabling of name column editing
- [x] Add propagation of name column editing state
- [x] Add validation of unique name
- [x] Add support for updating name on server side
- [x] Add regex support for names (1)
- [x] ~~Update unique name when editing?~~ (2)
- [x] Add user warning in column config modal
- [x] Make sure this also works with old sheet configs without `type="name"`
- [x] Add tests (at least for the Ajax API view)
- [x] Update the WIP documentation modal
- [x] Add check for empty name

## Notes

- (1) Only adding hardcoded regex for now, can make editable later.
- (2) Will implement this later if needed, not really relevant as it's only "used" internally (and not used much tbh)
