### ISSUE TITLE
Cleanup for v0.8.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#860]
Minor tasks here.

## Tasks

- [x] Fix description in the `sheet_edit_start` timeline event
- [x] Add iRODS backend checks in the two `get_irods_path()` functions in `samplesheets/serializers.py`
- [x] Rename `EDIT_JSON_ATTRS` to `MODEL_JSON_ATTRS`
