### ISSUE TITLE
Samplesheets: Add row deletion

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#868]
Separated from #834, because there'll be enough specific stuff to make this a separately relevant task.

## Spec/Notes/Etc

- Node deletion
   * Delete arcs as found in row
   * If node object is no longer in arcs and is not sample in assay, delete node object
   * If sample in study row is used in an assay, do not allow deletion
- **TBD:** What to do with deleting rows which are linked to related files in iRODS?

## TODO

- [x] Add main UI logic
- [x] Add server side logic
- [x] Add study table check for sample use in assays
- [x] Remove sample from UI sample list once deleted
- [x] Fix study row deletion (related to #902)
- [x] Assert behaviour when deleting all rows from a table (See also #870, #903)
- [x] Add note about iRODS data when deleting a row, if `irods_status==True`
- [x] Update controls during deletion similar to insertion
- [x] Update row numbers on delete
- [x] Update in-app docs
- [x] Test, test, test
