### ISSUE TITLE
Samplesheets: Enable protocol editing

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#871]
Required for #834. Pretty self explanatory really.

## Tasks

* [x] Set specific header and/or column type for protocol in rendering
* [x] Allow enabling/disabling protocol column editing in UI
* [x] Provide list of existing protocols to select from in the Ajax view
* [x] Provide protocol UUID in rendering
* [x] Set up editor for referred objects including protocol
* [x] Add saving of protocol data on the server
* [x] Enable default value
* [x] Update tests
* [x] Update help modal

## Notes

- Set up a separate editor for foreignkey references and switch with `cellEditorSelector`?
    * This could also be used in assay tables for study nodes!
