### ISSUE TITLE
Issues on the staging server

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#911]
Collecting these here since there are currently many.

## Tasks

- [ ] iRODS connection not working (DNS issue?)
- [ ] Email headers and site instance name not correctly set in staging (#907) (1)
- [x] SITE_SUBTITLE is not correctly displayed in staging (#777) (1)
- [ ] Davrods status = ???

## Notes

- (1) Generally it seems certain environment settings are simply not picked up. Will need to see if this is because of something wrong in SODAR Django config or in the Ansible playbook (or both?)

**Comment by mikkonie** [comment]
The staging server has since been completely redeployed using sodar-docker-compose, so this is no longer valid. If there are further issues, will open them in the appropriate repo. Closing.
