### ISSUE TITLE
Ontologyaccess: Add site app for ontology storage and access

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#937]
Needed for #699 and #688.

Technically, this could also be a site app plugin point within `samplesheets`. That app is getting super bloated already with the study/assay sub-apps and the vue app. Might as well set up a separate site app in project root.

## Planning

- Functionality
    * Store ontologies in a Django dabase model
        + Storing as list should be sufficient, not required as graph
        + ~~**TBD:** Object per entry or per model, with ontology as a JSON list?~~ Single objects are easier to search and extend plus they can be nicely indexed, so going with that
    * Provide simple UI for uploading/replacing .obo files
    * Provide Ajax view for searching/accessing db ontology
        + **TBD:** Is there also use for a REST API view?
- Parsing .obo files with Python
    * https://pypi.org/project/obonet/
    * https://pypi.org/project/fastobo/
        + [Docs](https://fastobo.readthedocs.io/en/latest/api/index.html#library-reference)
- Relevant .obo files
    * [HPO](https://hpo.jax.org/app/download/ontology)
    * [NCBITAXON](https://github.com/obophenotype/ncbitaxon/releases/tag/current)
    * https://bioportal.bioontology.org/ontologies
- Other references
    * [OBO v1.2 spec](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html)

## Tasks

- [x] Set up app skeleton with plugin
- [x] Create model
- [x] Create parsing code
- [x] Create simple upload UI
- [x] Create upload management command
- [x] Create initial Ajax view for ontology access
- [x] Test
