### ISSUE TITLE
Samplesheets: Add samplesheets ISAtab export

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#95]
Add the possibility to export ISAtab as a zip file.

## TODO

(Just writing things down for myself here)

* [x] Fix the parsing issue manifesting in Charite_Mundlos_Limb_Genomes (I forget to convert an ontology term)
* [x] Add assay writing
* [x] Add factor value parsing
* [x] Look into critical warnings for protocol export
* [x] Add factor export for study
* [x] Make sure headers are imported/exported everywhere
* [x] Ensure perform date field is properly converted
* [x] Add missing fields in db (see #581)
* [x] Add Zip archive serving
* [x] Fix comments parsing (still some dictionaries in there, oops!)
* [x] Fix sample parsing in assays (I had one job)
* [x] Test, test, test!
