### ISSUE TITLE
Cleanup for v0.9.0 release

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#950]
Small stuff here.

## Tasks

- [x] Cleanup study and assay app docstrings
- [x] Refactor redundant `self.raw_data_coll` in assay apps
- [x] Update author list
- [x] Change dev docs to readthedocs template
- [x] Fix `WARNING: html_static_path entry '_static' does not exist` in docs_dev
- [x] Update version numbers in samplesheets app and docs
