### ISSUE TITLE
Samplesheets: Improve ontology term ID clipboard copying

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#971]
I'll need to look into improving the copying of ontology term IDs to the clipboard. To clarify, this is related to copying only the IDs in the standard table view, not copying the entire ontology reference in `OntologyEditModal`.

I believe the current method is based on grabbing the ID from the accession URL, which is mostly based on flawed and non-working URLs. In valid URLs, the ID can't often even directly derived from the URL.

The better way would be to add the actual IDs in the table data in `rendering`, pass them when copying term IDs on the clipboard and update as necessary.

**TBD:** How to handle unknown IDs? (if someone has input either a term not in our db or a term with a typo or something)

@holtgrewe: Comments are welcome.

## Tasks

- [ ] Add term ID search helper to `ontologyaccess.api`
- [ ] Add additional ID copy attribute to ontology cell rendering when NOT in edit mode
- [ ] Copy the ID attribute when doing clipboard copy in table view
- [ ] Add tests where applicable
- [ ] Update editor help modal
