### ISSUE TITLE
Add iRODS admin app for locating orphan iRODS data

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#972]
We should add an iRODS admin site app for performing the following tasks:

- Add management command to check for iRODS file status
- Find collections / data objects with invalid paths in `/{zone}/projects/*`
    * Not corresponding to any study or assay
        + Iterate through project sample repository collections in iRODS
        + Orphan = study/assay `sodar_uuid` in path not found in project
    * Not corresponding to any landing zone (see #891)
        + Get all zones of a project EXCEPT those with the status of MOVED or DELETED
        + Get a list of paths for all of those with irodsbackend's `get_path(zone)`
        + Orphan = landing zones which is NOT in aforementioned list
- Display list of paths as a result to the user
    * **TBD:** Exact formatting? Simply paths separated with newline?
    * **TBD:** Add extra flag for downloading list as a text file (or just direct output in terminal?)
- No UI needed in the initial version, simply a management command
- Hard imports to models in `samplesheets` and `landingzones` apps are OK, no need to develop an extra backend for this
- Use `irodsbackend` for iRODS queries
    * Expanding `irodsbackend` with new helpers is perfectly fine, if applicable

## Tasks

- [x] Create new app called `irodsadmin`
- [x] Create a management command `irodsorphans` for aforementioned actions
- [x] Test? (see #945)
- [x] Update docs where applicable

**Comment by mikkonie** [comment]
unassigned @stolpeo
