### ISSUE TITLE
Rewrite Vue app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#994]
**Update 2025-11:** *Time to rip off the band-aid and get this over with.*

Vue2 has been EOL for a long time. Many critical dependencies are not receiving updates any more. This has been put off for too long: it's time to rewrite the samplesheets Vue app in Vue3.

User-facing functionality should initially be a 100% match to the legacy Vue2 app. New major features and improvements will be done once the old app has been retired.

Internally many things should be rethought. The most glaring issues are:

- Proper routing of app-internal views
- Proper storage of data and access between components (using Vue3 best practices of course)
- Typescript vs Javascript?
- Styling (IMHO we should still be using Bootstrap to maintain maximum consistency with SODAR and SODAR Core)

For v1.3, the new app will be provided as an opt-in "experimental" version of the app on the side of the original app. Users can choose to switch to the new app via a user app setting.

Once I'm satisfied with how well the new app works, the old app will be retired for good. Hopefully we can already do this in v1.4.

**If** this turns out to be a too much of a mammoth of a task, or there is some specific reason to get end user feedback on the way, I may also opt to provide some kind of an MVP version for v1.3 and continue development incrementally in future versions. This is not the intention though. I'd rather get this done to the state of the Vue2 app ASAP.

At the time of writing I'm still working through the spec and tasks and thinking of some decisions, so these will most likely constantly evolve during the development of this feature.

## Spec

- Rewrite app with Vue3
    * ~~**TBD:** Typescript or Javascript?~~
        + Going with Typescript, unless some strong reasons not to do this arise
        + Can't really figure out any downsides, despite strong typing generally being a somewhat overhyped issue IMHO ;)
    * ~~**TBD:** Vue3 Options API or Composition API?~~
        + Going with Composition API: less boilerplate, way more flexible
        + AG Grid supports both
        + Oliver says Composition API worked well in VarFish
        + Might be a bit higher initial cost to port the Vue2 API stuff, but IMHO worth it
- Maintain both app versions for (at least) one major release
    * Allow users to switch between apps with user setting
- Once new app is 100% functional and considered stable, remove old app
- Routing
    * Figure out how to nicely use Vue router
    * ~~Serving integrated app from `/static` makes router mess up URLs by default~~
        + Fixable with `createWebHashHistory()`
- Styling
    * See [BootstrapVueNext](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html)
    * Issue: some CSS modifications don't work within bootstrap-vue-next components if set in parent components
        + Workaround: set a global CSS override server side
        + **Q:** Anyone have better ideas?
- Review existing vue app issues, modify/close as needed relating to these plans

## Tasks

- [x] Set up hello world Vue3 app
- [x] Add user setting to enable new app
- [x] Set up Django integration of new app
- [x] Delete unnecessary stuff from default app
- [x] Add app header skeleton
- [x] Add context retrieval and pinia storage
- [x] Add Bootstrap styling
- [x] Add initial operations dropdown links
- [x] Figure out solution/workaround for BootstrapVueNext CSS override issue
- [x] Simplify common `appStore` variable getting
- [x] Add grid store
- [x] Add routing for study/overview views using vue-router (see issues)
- [x] Add sheet overview retrieval and display
- [x] Fix navigation for non-default initial URL
- [x] Add study table retrieval
- [x] Add `SheetTableHeader` component
- [x] Add `IrodsStatsBadge` component
- [x] Add `IrodsButtons` component
- [x] Add parser warning view
- [x] Set up modal display, test with `TableDetailModal` first
- [x] Add routing for assay navigation (once rendered)
- [x] Add scrolling to correct table from nav dropdown if in the same view
- [x] Ensure study navigation works with multi-study investigation
- [x] Move generic loading template into separate component
- [x] Update app to work as expected with no sheets
- [x] Add `SheetTable` component
- [x] Add `AssayShortcutCard` component
- [x] Fix typescript warnings in `StudyView` and `AssayShortcutCard`
- [x] Rename `gridStore` to `tableStore`, refactor typescript
- [x] Move `modals` under `components`
- [x] Add MVP sheet table rendering with ag-grid
- [x] Fix ag-grid deprecation warnings
- [x] Enable proper styling for ag-grid
- [x] Fix row number column width
- [x] Fix cell padding
- [x] Disable row highlighting
- [x] Disable iRODS column click highlighting and kb navigation
- [x] Fix forced left side padding in `IrodsButtons`
- [x] Add `DataCellRenderer`
- [x] Add `IrodsButtonsRenderer`
- [x] Add `StudyShortcutsRenderer`
- [x] Add `StudyShortcutModal`
- [x] Add `IrodsDirModal`
- [x] Add custom template slot in `ModalHeader`
- [x] Add `ColumnToggleModal`
- [x] Refactor store imports to stop confusing PyCharm autocomplete
- [x] Add context data alerts display
- [x] Add table resizing to fit content
- [x] Add visual signifier for new app version
- [x] Add `WinExportModal`
- [x] Fix `AssayShortcutCard` layout alignment
- [x] Fix study navigation on reload
- [x] Fix study refresh on navigation from overview
- [x] Fix navigation tab button states
- [x] Fix `OverviewView` study and assay links
- [x] Fix `OverviewView` navigation on reload
- [x] Handle TODOs in `OverviewView`
- [x] Fix sheet ops dropdown replace/delete links visible with no sheets in project
- [x] Fix new app warning only showing if delete requests are active
- [x] Fix assay iRODS modal opening in assay shortcuts
- [x] Fix cell renderer component modal opening on nav from overview without study reload
- [x] Add table filtering
- [x] Add notification mechanism
- [x] Unify naming in `constants.ts`
- [x] Add clipboard copying in table detail modal
- [x] Unify function declaration syntax
- [ ] ~~Fix `valueFormatter` warning~~ To be done in #2390
- [x] Update documentation for Vue3 app
- [x] Cleanup `README.md`
- [x] Fix build errors
- [x] Ensure building into correct staticfiles dir (e.g. `samplesheets-vue3`)
- [x] Add app building to Docker image
- [x] Ensure app Django integration works in production build mode
- [x] Add basic sanity check unit tests
- [x] Add new app to CI
- [x] Ensure Vue3 app tests work in CI
- [x] Add server-side smoke test for Vue3 app rendering, ensure this works in CI

**Comment by mikkonie** [comment]
For future reference, this turned out to be a very useful tutorial on integrating a Vue3 Vite app with Django: https://dkane.net/2024/getting-vuejs-3-to-work-nicely-with-django/

**Comment by mikkonie** [comment]
This work is coming along nicely (when I have time for it), but it's shaping to be one pretty huge commit. At the moment my thinking is to split this into separate issues as follows:

- App structure, rendering and integration into Django (this issue)
- Tests
- Edit mode support

This way the commit size should be somewhat manageable and I don't have to keep rebasing a huge workbranch for weeks ;)

Also, this will enable me to deploy a work branch in staging and allow some power users to test out the app before it's done.

I'll be updating the task list and creating new issues accordingly.

**Comment by mikkonie** [comment]
Looks like I've messed something up in CI:

```
WARNINGS:
?: (django_vite.W001) Cannot read Vite manifest file for app default at /home/runner/work/sodar-server/sodar-server/samplesheets/vue3app/dist/samplesheets-vue3/manifest.json : [Errno 2] No such file or directory: '/home/runner/work/sodar-server/sodar-server/samplesheets/vue3app/dist/samplesheets-vue3/manifest.json'
	HINT: Make sure you have generated a manifest file, and that DJANGO_VITE["default"]["manifest_path"] points to the correct location.
```

**Update:** Oops, was accidentally trying to access app in production mode from django-vite using the test config.

**Comment by mikkonie** [comment]
Done. Phew. Alas, work continues in #2389 and #2390.
