### ISSUE TITLE
Samplesheets: Allow per-project restriction of column config updates

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#995]
Initially modifying column configurations was allowed for superusers, owners and delegates only. Afterwards I was instructed to change it so that contributors can also do it.

In a meeting with Dieter and Benedikt we discovered a use case where this should be restricted on a per-project basis, possibly to superusers only.

## Spec

- Add a samplesheets app setting `edit_config_min_role` with `PROJECT` scope
    * Options: `superuser`, `project owner`, `project delegate`, `project contributor`
    * Default: `project contributor`
    * Requires the implementation of undefined##undefined     
- Pass an `can_edit_config` param to vue app in Ajax view
    * Check related user role and app setting in Django
    * Should probably go under `edit_context` as this is only relevant when in edit mode
    * **NOTE:** Superusers will be able to do this no matter what
- Enable/disable column config controls in vue app based on aforementioned parameter
    * Check perms in `gridUtils.js` (line 275+), do not use `HeaderEditRenderer` if user lacks minimum perm
- Add permission control to `SheetEditConfigAjaxView` to make sure unauthorized users can't access that directly

## Tasks

- [x] Add samplesheets app setting
- [x] Pass setting value to vue app in `edit_context`
- [x] Enable/disable column config in vue app based on setting
- [x] Check setting in `SheetEditConfigAjaxView`
- [x] Add tests (NOTE: also vue app ui tests!)

**Comment by mikkonie** [comment]
unassigned @stolpeo
